### ISSUE TITLE
openeo-python-client/openeo/imagecollection.py

### ISSUE THREAD

**Issue by ms801221** [Open-EO/openeo-python-client#1]
- def combinebands 
  - suggestion renaming: --> def layerstack
  - suggestion renaming: --> def stack
  - suggestion restructuring: implementing as an 'imagecollection' constructor, using an undefined amount of bands as input parameters? Then 'bandscollection' could be another class.
- def reduceByTime
  - suggestion restructuring: --> def filter(string); query parameter 'string' for possible capabilities, mathematical symbols or specific strings as 'inlist', values, logical operators; create a filter of these exports.
    - e.g. imagecoll.filter('date > 2017-01-01 OR date < 2016-05-01')

**Comment by jdries** [comment]
For reduceByTime, we should discussed these alternatives:

- First groupBy(dim=time,list_of_intervals), then aggregate
- Pandas uses resample, but this may cause confusion as it has a temporal and spatial interpretation
- Composite is  a term used often in remote sensing

**Comment by jdries** [comment]
Issue cleanup: no longer relevant, processes have been redefined.
