### ISSUE TITLE
Abstraction layer for the authentication

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-python-client#10]
Due to different (but also similar) authentication methods of the providers it makes probably sense to make an abstraction for authentication inside of a session. 
One possibility:

- Add abstract Authentication class to the session class, which will be initialized at the constructor.

**Comment by m-mohr** [comment]
That makes sense as we just added two authentication protocols to the API: OpenID Connect and HTTP Basic. Would be good if clients support both with priority to OpenID Connect, of couse.

**Comment by bgoesswe** [comment]
Created an Abstraction Auth class See #11 , 
Right now supported: Bearer Token and No Auth instances.
