### ISSUE TITLE
hardcoded dimension names

### ISSUE THREAD

**Issue by lforesta** [Open-EO/openeo-python-client#116]
in openeo/rest/imagecollectionclient.py some dimension names are hardcoded

- _reduce_time() -> 'temporal'
- band() -> 'spectral_bands'

these clash with back-ends defining different names for these dimensions, e.g. see [https://earthengine.openeo.org/v0.4/collections/COPERNICUS/S2](https://earthengine.openeo.org/v0.4/collections/COPERNICUS/S2) under properties/cube:dimensions .

**Comment by soxofaan** [comment]
related to #76 and #93

**Comment by soxofaan** [comment]
merged in master

**Comment by lforesta** [comment]
Can I ask how/where does the client get this information from the backend collections endpoint?
With which version(s) of STAC is the client compatible?

**Comment by soxofaan** [comment]
The client tries to be bit forgiving about this and currently looks for dimension names here:
- `cube:dimensions` (stac 0.9.0 style per https://openeo.org/documentation/1.0/developers/api/reference.html#operation/describe-collection)
- `properties > cube:dimensions` (stac 0.6.2 per https://openeo.org/documentation/0.4/developers/api/reference.html#tag/EO-Data-Discovery/paths/~1collections~1{collection_id}/get

also see https://github.com/Open-EO/openeo-python-client/blob/master/openeo/metadata.py#L133-L204
