### ISSUE TITLE
Running the Python client on computers with restrictions to install software

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-python-client#12]
Public authorities / NGOs / companies may have restrictions to install software (as e.g. Python, R) on their office computers. A remotely hosted openEO web editor is a way for them also to use openEO, but is it also possible to run the openEO client using a portable python installation? Would be nice to check this and add a hint to the documentation.

**Comment by jdries** [comment]
In it's current state, the Python client only has a few dependencies, but it indeed requires Python in some other form :-). Not sure what you mean with 'portable python' though, can you clarify?
Also note that there exist other systems, such as Jupyter notebooks, that allow you to run Python in a browser environment without installing anything on your computer. Perhaps that's a good solution?
(e.g. https://proba-v-mep.esa.int/notebooks)

**Comment by m-mohr** [comment]
At least on Windows it is common that there are "portable" program packages that can run without installation, i.e. unzip and run. This is useful in cases when you have restricted Windows accounts, which can't install new software. This is often the case in public authorities and "non-technology" companies. For Python such a package seem to be provided by http://portablepython.com/ or https://winpython.github.io/ for example. The question (from a EODC forum participant) was whether the openEO client library would run with such a portable Python package or not.
Python notebooks sound like a good alternative, too. 
I think it would be a good idea to mention those alternatives in the Python client readme.

**Comment by jdries** [comment]
Issue cleanup, closing this one: various solutions exists, and we keep the core dependencies of the Python client to a minimum. The best solution usually depends on the specific situation of a user.
