### ISSUE TITLE
"imagery" vs "collection"

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-python-client#13]
As also discussed in the core api (https://github.com/Open-EO/openeo-api/issues/49) 
, the processes will define the keyword of the process graph. 
Right now there is a python file imagery.py and imagecollection.py for the keywords "imagery" and "collection" that do basically the same, the redundancy should be removed in the future.

**Comment by soxofaan** [comment]
as far as I currently understand:

- `openeo/imagecollection.py` is the base class for image collections in openeo-python-client, openeo-geopyspark-driver, ...
- `openeo/rest/imagery.py` is old, deprecated 0.3-style and will probably be removed at some point
- `openeo/rest/imagecollectionclient.py` is new 0.4-style

**Comment by jdries** [comment]
correct understanding. ImageCollection is basically copied from earth engine, but something like 'datacube' would also be appropriate. We never really came to a conclusion on this, but if we still want to change it then we shouldn't wait too long.

**Comment by jdries** [comment]
Closing: imagery.py no longer exists.
