### ISSUE TITLE
Complex reducer/apply

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-python-client#130]
At the moment if you need to define a process graph to reduce or apply to a dimension, users have to create PGNode constructs by themselves. It would be nice if the user would be able to create these graphs the same way as with the datacube. But to do that you would need to get a datacube without loading a collection.
I am not sure how to solve that issue without too much confusion for users, but maybe something like a new reducer class (maybe also inheriting from imagecollection). 
The datacube class could also be used, but then there needs to be an interface to get it (maybe from the initial datacube), disadvantage of this is that the methods should be limited for the reducer usage.

**Comment by soxofaan** [comment]
Interesting point.

the `PGNode` class is at the moment meant for internal use, and ideally the user should not work with it directly.

Instead ImageCollectionClient and DataCube define mathematical operators that should cover a lot of "band math" spectral `reduce` cases. These operators could also be used for `apply` usage (see e.g. #123 )

But indeed, for use cases that are a bit more advanced than mathematical operators (e.g. adding a UDF node), we need something more approachable

**Comment by soxofaan** [comment]
Building child processes/callbacks is now covered with the `ProcessBuilder` class, documented at https://open-eo.github.io/openeo-python-client/processes.html#processes-with-child-callbacks
