### ISSUE TITLE
Drop API v0.4 support

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#134]
This is a placeholder ticket to be able to mark/tag code that is specific to API v0.4 (or older)

**Comment by m-mohr** [comment]
Is there a timeline for dropping 0.4 support? I'm just wondering whether I should just support 1.0+ in my Jupyter Lab work or whether I still need to invest the time to support 0.4? (I hope I won't.)

**Comment by soxofaan** [comment]
We didn't decide on a timeline yet to remove the 0.4 support

The 0.4 support in the client is just in the phase "keep the 0.4 code paths, but don't touch them anymore"
New features and functionality is not added anymore (unless it's in the version-independent code paths)

I don't think you should bother with 0.4 for new features either

**Comment by soxofaan** [comment]
I think pre-1.0.0 support is now fully dropped with commits listed above, so closing this ticket
