### ISSUE TITLE
filter_bbox argument order

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#136]
the argument order of filter_bbox in ImageCollection/Datacube is currently:

        def filter_bbox(self, west, east, north, south, crs=None, base=None, height=None) 

the argument order in the filter_bbox documentation https://openeo.org/documentation/1.0/processes.html#filter_bbox is :

     west, south, east, north, base, height, crs

This apparently confuses users.

Possible solutions:
1. change order in python client to be closer to API. This might break existing code silently.
2. use keyword-only  arguments (https://www.python.org/dev/peps/pep-3102/) to enforce explicit naming of the arguments. This probably breaks existing code, but with a clear error message.
3. keep things how they are in the 0.4 API style `ImageCollectionClient`, but use keyword-only arguments in 1.0 API style `DataCube`. This probably doesn't break existing code (because 1.0 is not much in use at the moment I think), but might add to the confusion.

**Comment by loicdtx** [comment]
I was about to suggest changing the order to west, south, east, north, so as to align on the order used for bboxes by shapely, rasterio, fiona, postgis, open data cube, etc. Good that I checked existing issues before.

That would make using the method less error prone. For instance to query a 1 square degree bbox around Paris I could do:

```
from shapely.geometry import Point

bbox = Point(2.35, 48.85).buffer(1).bounds
coll = coll.filter_bbox(*bbox, crs=4326)
```

which is less prone to error than doing

```
coll = coll.filter_bbox(west=bbox[0], east=bbox[2], north=bbox[3], south=bbox[1])
```

**Comment by soxofaan** [comment]
@jdries   what's your call on this?

**Comment by jdries** [comment]
To come up with a solution that is backwards compatible, we could simply support shapely bounds directly?

Either add 'geometry' keyword argument:
def filter_bbox(self, west=None, east=None, north=None, south=None, crs=None, base=None, height=None, geometry=None) -> 'DataCube':

or overload the 'west' keyword argument:
def filter_bbox(self, west, east=None, north=None, south=None, crs=None, base=None, height=None) -> 'DataCube':

in which case we'd need to check on the type of west? Unfortunately changing the name won't work..

Or simply create a new method? filter_spatial sounds plausible to me...

**Comment by loicdtx** [comment]
I'd suggest `filter_bounds` instead of `filter_spatial`, with an explanation in the docstring that it does exactly the same as `filter_bbox` but the method's argument are ordered following the geojson specification of a bbox.

**Comment by soxofaan** [comment]
I'm not a fan of adding a new method just to change argument order. The openEO spec docs and a lot of examples already use `filter_bbox`, so adding a differently named method to implement  https://openeo.org/documentation/1.0/processes.html#filter_bbox  will be confusing.

I like the idea of making it possible to pass a shapely geometry directly to `filter_bbox` (or a new method), but that does not solve the original issue of inconsistent argument order in the original `filter_bbox`.

FYI: `filter_spatial` is already defined as a process: https://openeo.org/documentation/1.0/processes.html#filter_spatial and involves masking by the geometry on top of the bbox crop.

Another solution is to leverage keyword-only arguments like I suggested before, while still supporting the old argument order (but raise a deprecation warning). Roughly like this:

    def filter_bbox(self, *args, *, west=None, south=None, east=None, north=None):
        if args:
             if len(args) == 4:
                 # handle old west-east-north-south order
                 warning("deprecated usage, will be removed. Use keyword args instead") 
                 west, east, north, south = args
             elif len(args) == 1:
                  if isinstance(args[0], Geometry):
                      # get bbox from bounds
                      west, south, east, north = args[0].bounds
                  elif isinstance(args[0], (tuple, list)) and len(args[0]) == 4:
                      west, south, east, north = args[0]
        ....

This still supports old calls (but deprecation warning is raised)

       filter_bbox(west, east, north, south)

keyword style is promoted

      filter_bbox(west=west, south=south, east=east, north=norht)

passing a tuple/list is also allowed (using standard bound order):

     filter_bbox([west, south, east, north])

and passing shapely geometries is also allowed

      filter_bbox(shape)
      # and even:
      filter_bbox(shape.bounds)

**Comment by jdries** [comment]
@soxofaan  your proposal seems like the best tradeoff and backwards compatible.
Feel free to go ahead with this.

**Comment by soxofaan** [comment]
implemented:
- legacy behaviour with 4 positional args is preserved
- now also accept single positional argument (or `bbox` kwarg): bounding box list/tuple/dict or shapely geometry
