### ISSUE TITLE
support load_collection "properties" argument

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-python-client#141]
The OpenEO API mentions a "properties" argument to [load_collection](https://openeo.org/documentation/1.0/processes.html#load_collection) to further limit the data in the collection; it is a collection of predicates to match certain collection metadata properties against.

The Python client should provide a way to specify these predicates in code and add them to the load_collection process in the process graph.

**Comment by lforesta** [comment]
@m-mohr are the properties working now in the API?

**Comment by m-mohr** [comment]
Yes, should work, but still haven't seen an implementation...

**Comment by lforesta** [comment]
Do they need to be specified under a specific keyword on the collections/<collection-id> endpoint?
If not, how are the clients supposed to retrieve these fields?

@m-mohr for [this collection](https://earthengine.openeo.org/v1.0/collections/COPERNICUS/S2), would it be possible to query using the property `summaries/gee:schema/CLOUDY_PIXEL_PERCENTAGE`?

**Comment by m-mohr** [comment]
They are meant to be part of the summaries. Here's a collection example from STAC:

```js
{
  "stac_version": "0.9.0",
  "stac_extensions": [],
  "id": "COPERNICUS/S2",
  "title": "Sentinel-2 MSI: MultiSpectral Instrument, Level-1C",
  "description": "...",
  "license": "proprietary",
  "providers": [...],
  "extent": {
    "spatial": {
      "bbox": [[-180,-56,180,83]]
    },
    "temporal": {
      "interval": [[ "2015-06-23T00:00:00Z", null]]
    }
  },
  "summaries": {
    "datetime":  {
      "min": "2015-06-23T00:00:00Z",
      "max": "2019-07-10T13:44:56Z"
    },
    "platform": ["sentinel-2a","sentinel-2b"],
    "constellation": ["sentinel-2"],
    "instruments": ["msi"],
    "view:off_nadir": {
      "min": 0.0,
      "max": 100
    },
    "view:sun_elevation": {
      "min": 6.78,
      "max": 89.9
    },
    "sci:citation": ["Copernicus Sentinel data [Year]"],
    "gsd": [10,30,60],
    "proj:epsg": [32601,32602,32603,32604,32605,32606,32607,32608,32609,32610,32611,32612,32613,32614,32615,32616,32617,32618,32619,32620,32621,32622,32623,32624,32625,32626,32627,32628,32629,32630,32631,32632,32633,32634,32635,32636,32637,32638,32639,32640,32641,32642,32643,32644,32645,32646,32647,32648,32649,32650,32651,32652,32653,32654,32655,32656,32657,32658,32659,32660],
    "eo:bands": [...]
  },
  "links": [...]
}
```

There I'd expect to be able to query for individual platforms for example.

The issue with gee:schema/CLOUDY_PIXEL_PERCENTAGE is that it's hidden in a complex object and there's no way to look into them in queries. That's something I need to fix with google. The things in gee:schema properties should be a level up directly in the summaries somehow. Issue there is that google doesn't give any clue about the data in there except for the data type so you don't really know what actual values you could filter on...

**Comment by lforesta** [comment]
perfect, thanks!

**Comment by jdries** [comment]
This test seems to indicate that this is now possible and thus solved:
https://github.com/Open-EO/openeo-python-client/blob/e230294afb19ab70753d24100c7f5d6ff6efead9/tests/rest/datacube/test_datacube100.py#L260

**Comment by Githopp** [comment]
Hey sorry for commenting on a closed Issue, but where can I see if and what STAC metadata is implemented? 
Do any backends allow to query on cloud cover as for now?

```
Because this:
geedatacube = gee.load_collection("COPERNICUS/S2_SR",
                               spatial_extent = bbox,
                               temporal_extent = timeframe,
                               bands = bands,
                               properties={"eo:cloud_cover": PGNode(process_id="between", arguments={"x": {"from_parameter": "value"}, "min": 0, "max": 50})})
geedatacube.download("test.tif",format="GTIFF-THUMB")
```

Results in : 
`OpenEoApiError: [500] ProcessArgumentUnsupported: Process 'load_collection' does not support the following arguments: properties`

**Comment by m-mohr** [comment]
Unfortunately, GEE doesn't support properties right now (and GEE for openEO is also currently not maintained).

**Comment by jdries** [comment]
It works on the VITO backend, we implemented it for cloudcover and a few other properties, like relative orbit number and orbit direction in our S1 collections.

**Comment by Githopp** [comment]
@jdries when I try the test_datacube code on the TERRASCOPE_S2_TOC_V2 data I get a
`OpenEoApiError: [500] unknown: process between is not supported`
error. Which is weird because the process is listed. 
Is this a bug, or am I missing something?

```
import openeo
from openeo.internal.graph_building import PGNode

bbox = {'west': 8.44,'south': 54.34,'east': 8.99,'north': 54.6,'crs': 'EPSG:4326'}
bands = ["B04", "B03", "B02"]
dates = ("2021-03-06", "2021-03-11")
terrascope="TERRASCOPE_S2_TOC_V2"

def between(min, max) -> PGNode:
    return PGNode(process_id="between", arguments={"x": {"from_parameter": "value"}, "min": min, "max": max})

con = openeo.connect("https://openeo.vito.be").authenticate_oidc(provider_id="egi")
cube = con.load_collection(terrascope, bbox, dates,bands,properties={"eo:cloud_cover": between(min=0, max=50)})
                           
cube.download("basic.tiff", format="GTIFF")
```

**Comment by jdries** [comment]
The problem is that we need to translate these graphs into OpenSearch and STAC queries, and that simply has not been done yet for every possible process. So there's a lot of processes that we support in another context, but not for property filtering.
Would 'between' be your preferred process for cloud cover filtering? I would rather expect something like 'smaller than'?

**Comment by Githopp** [comment]
Yes less than equal was the logical step for me, too. 
At first I tried just  {"eo:cloud_cover": {"lt": 50}} 
The between example just came in handy, because if its working in the test case, it has to work right? :)

And to be honest I find working with process graphs rather complicated, because I dont really know what the backend expects/offers, looking at the {"from_parameter": "value"} part.
I assume this would be correct if the process is implemented:
{"eo:cloud_cover": PGNode(process_id="lte", arguments={"x": {"from_parameter": "value"}, "y": 50})}

"Between" as filter process on the other hand would be more flexible, like when somebody wants just pictures with clouds, eg. for training/testing a cloud detector for example.

**Comment by m-mohr** [comment]
> Hey sorry for commenting on a closed Issue, but where can I see if and what STAC metadata is implemented?
> Do any backends allow to query on cloud cover as for now?

By the way, thanks for bringing this up. Indeed, it's currently hard to understand what queries are allowed/possible. Thus, I've opened https://github.com/Open-EO/openeo-api/issues/396 to make it easier to understand what people can query on.

**Comment by soxofaan** [comment]
FYI: to build the properties filter, you don't have to use the `PGNode` approach which can be cumbersome indeed.

See this test for a more compact approach, based on processes defined in `openeo.processes`:
https://github.com/Open-EO/openeo-python-client/blob/e344c4c105e8d5b13e16d99bc19baeb92ca79cf0/tests/rest/datacube/test_datacube100.py#L606-L619

note that this test also uses the "between" process, but that does not necessarily means that it is supported by a backend at the moment. The test just tests if a valid process graph is constructed from the code flow.

**Comment by m-mohr** [comment]
Oh yes, that's looking much better and that's what I also thought it should look like in my comment above.
