### ISSUE TITLE
Don't require users to choose an API version

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-python-client#142]
Well-known discovery was added to the API so that users by default don't have to choose an API version, which they usually doesn't know anything about. Therefore the API docs says:

> By default, a client SHOULD connect to the most recent production-ready version it supports. The most recent version is determined by comparing the version numbers according to rules from Semantic Versioning, especially §11. Clients MAY let users choose to connect to versions that are not production-ready versions or outdated.

All clients I'm aware of do this already, but the Python client requires users to use "direct Urls", e.g. https://earthengine.openeo.org/api/v1.0 instead of just allowing to pass https://earthengine.openeo.org and then the clients chooses the most recent production-ready version supported by the client. I guess that's what users want to use in most cases anyway. So I think this should also be implemented in the Python client.

**Comment by jdries** [comment]
Added an implementation in python client as well!
