### ISSUE TITLE
How to perform datacube processes on every available image in the temporal range

### ISSUE THREAD

**Issue by jameshgrn** [Open-EO/openeo-python-client#148]
Hi all, 

Wondering if there is a way to perform an operation (NDWI, NDVI) on every available image between the start and dates in a datacube?

**Comment by soxofaan** [comment]
that is actually the default behavior if you do something like

```python
cube = connection.load_collection(...).filter_temporal(start, end)
ndvi = cube.ndvi()
```
the resulting `ndvi` variable points to a timeseries (cube) of ndvi images

**Comment by jdries** [comment]
Seems like this question was answered, so closing!
