### ISSUE TITLE
Please mention that it's Python3

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-python-client#15]
I tried to go through the hackathon tasks in [openeo-hackathon/test-cases/README.md](https://github.com/Open-EO/openeo-hackathon/blob/99f0d3d5d264bb52668218faa6ec8682dc7c0f5b/test-cases/README.md) and stumbled across a few things. I'll open one issue for each. I'm not a dedicated Python guy either, although I've used it before (at least a little bit).

The very first task was:
> Please install one of the openEO clients.

I managed to do so after figuring out that I have to use Python3. I guessed that using Python2.7 was the error because I was getting an `invalid syntax` error:

```
 Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "openeo/__init__.py", line 17, in <module>
    from .catalog import EOProduct
  File "openeo/catalog.py", line 11
    def collection_identifier(self) -> str:
                                    ^
SyntaxError: invalid syntax
```

Could you please specifically mention that Python3 is required? This would make "getting started" easier for users of all levels. Also, a hint that the dependency installation has to be done with `pip3` might be helpful, too.

After using `python3` and `pip3` (instead of `python` and `pip`) the installation worked fine on my Ubuntu 16.04 machine :+1:

**Comment by bgoesswe** [comment]
Added Python and pip version to the README.md
