### ISSUE TITLE
Capabilities request is missing

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-python-client#16]
The second part of the first task in [openeo-hackathon/test-cases/README.md](https://github.com/Open-EO/openeo-hackathon/blob/99f0d3d5d264bb52668218faa6ec8682dc7c0f5b/test-cases/README.md) is:
> Make sure that the client is properly working by connecting to one the back-ends and requesting the capabilities that are provided by the back-end.

The [API docs](https://open-eo.github.io/openeo-python-client/) linked in this repo's README were my first choice to look up how to do that, but they don't include anything related to a `capabilities` request.

Indeed the word "capabilities" doesn't appear anywhere in this repo ([full search](https://github.com/Open-EO/openeo-python-client/search?q=capabilities&unscoped_q=capabilities)).

**Comment by m-mohr** [comment]
Seems to be solved.
