### ISSUE TITLE
Give users the full process instead of just the graph

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-python-client#160]
In general, but especially also in the QGIS plugin and the Web Editor, openEO processes in JSON need to be fully defined including their potential metadata (see example 1), i.e. it is not enough to just list the graph nodes (see example 2). Unfortunately, the R client and Python client export the graphs without their metadata. This leads reportedly to some confusion when users try to copy/paste the "incomplete" processes into the Web Editor, QGIS Plugin or the Hub for example, which then can't handle them properly. Therefore, I'd really like to see that the R and Python clients print out the full process (see example 1).

As this is a 0.4/1.0 change, it may also be tackled with #125?

Example 1:
```json
{
  "process_graph": {
    "1": {
      "process_id": "add",
      "arguments": {
        "x": 1,
        "y": 2
      },
      "result": true
    }
  }
}
```

Example 2:
```json
{
  "1": {
    "process_id": "add",
    "arguments": {
      "x": 1,
      "y": 2
    },
    "result": true
  }
}
```

**Comment by soxofaan** [comment]
Valid point,

in 4a3d6f9b8b2c115dfe2b3f2d8796b89e7d1a5d91 I recently added `to_json` to generate a JSON representation of a DataCube. Maybe we can add that `{"process_graph": ...}` wrapper there? Or do you have a particular UI in mind on how users would want to get a JSON reprentation of their process/process graph?


FYI: #125  is roughly just an "epic" style ticket, to aggregate other tickets and small commit. I think we can close that ticket now.

**Comment by m-mohr** [comment]
I think that is up to the client library to decide, depending on how best practices evolved there (e.g. for JS it is always toJSON).

In some examples I've also seen this `.graph` property, which should likely be changed (or removed?).

**Comment by soxofaan** [comment]
that `.graph` property is mainly for internal use.
standard users should use this `to_json` method

**Comment by m-mohr** [comment]
Then better remove it from all examples and replace it with to_json, otherwise users will use it.

**Comment by soxofaan** [comment]
done
