### ISSUE TITLE
process_id 'reduce' hard-coded in ImageCollectionClient

### ISSUE THREAD

**Issue by lforesta** [Open-EO/openeo-python-client#161]
We now have `reduce_dimension` and `reduce_dimension_binary` in processes.openeo.org, but the class `ImageCollectionClient` hard-codes the old reduce process (`process_id = 'reduce'`) as a process to be used in 4 methods:

- band()
https://github.com/Open-EO/openeo-python-client/blob/master/openeo/rest/imagecollectionclient.py#L166

- reduce_bands_udf()
https://github.com/Open-EO/openeo-python-client/blob/master/openeo/rest/imagecollectionclient.py#L594

- reduce_temporal_udf()
https://github.com/Open-EO/openeo-python-client/blob/master/openeo/rest/imagecollectionclient.py#L632

- _reduce_time()
https://github.com/Open-EO/openeo-python-client/blob/master/openeo/rest/imagecollectionclient.py#L671

which then results in the following exception being raised:
`openeo.rest.connection.OpenEoApiError: [500] 500: Process 'reduce' could not be found in the list of processes.`

An easy fix is to hard-code `reduce_dimension` instead of `reduce`. Maybe a user could flag to use the binary version if they know the back-end supports it?

**Comment by jdries** [comment]
@lforesta that class is essentially the 0.4.0 code path of the client.
The client selects that path if the backend declares 0.4.0 as it's production version. Can you check this on your side?

**Comment by lforesta** [comment]
Thanks for the quick answer. For both the 1.0.0 and 0.4.0, the flag is set s False, what happens in this case? Must one of them be True? Note: this is my local back-end I'm working with.

**Comment by lforesta** [comment]
I was actually explicitly using the following form an old example:
`from openeo.rest.imagecollectionclient import ImageCollectionClient`

I now switched to `openeo.connect.imgaecollection` and I don't get the exception anymore. I'll close the issue.

**Comment by soxofaan** [comment]
FYI: indeed, you should normally not have to import `ImageCollectionClient` explicitly,
just do 
```
import openeo
con = openeo.connect(...)
cube = con.load_collection(...)
```
