### ISSUE TITLE
Windows install issue

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-python-client#162]
we tried to use the python client and when we try to import the openeo,
we got the following error and don’t know how to fix it:
 
>>> import openeo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'openeo'
 
 
We have the Windowsx64 – Version of Python, the Version 3.9.0 and the 20H2 Version of Windows 10.
After problems with numpy, we installed the older numpy – Version like the workaround says (http://pyhub.de/?p=418).
 
Can you help us?

**Comment by jdries** [comment]
Not finding the module means that either the install failed entirely, or you installed it to a location that's not on the pythonpath of the session that you're using to test.
So can you check first if installation actually succeeded? If it did, than you can navigate to your Python 'site-packages' directory, and openeo should be there.

**Comment by bgoesswe** [comment]
Thanks for the help, I just copied this issue, because I got asked by someone via mail. 
But it seems to be fixed now and a problem with their PyCharm installation
