### ISSUE TITLE
mask() alters pixel values

### ISSUE THREAD

**Issue by fdetsch** [Open-EO/openeo-python-client#165]
I was following the [Basic Usage](https://open-eo.github.io/openeo-python-client/basics.html) tutorial to apply a pixel mask to Sentinel-2 NDWI layers and noticed that pixel values for non-masked (ndwi.tif) and masked output (ndwi_masked.tif) differ. See the value ranges that I included in the comments, or simply compare the console output from `img.read(1)[0]` and `img1.read(1)[0]` to verify, or plot both layers with identical zlim.

```python
import openeo
import rasterio
import numpy as np

connection = openeo.connect("https://openeo.vito.be").authenticate_basic("test", "test123")


### . ndwi ----

sentinel2_data_cube = connection.load_collection(
  "SENTINEL2_L2A_SENTINELHUB"
  , spatial_extent = {'west':5.151836872,'east':5.1533818244,'south':51.181925592,'north':51.184696360,'crs':4326}
  , temporal_extent = ["2020-05-01", "2020-05-10"]
  , bands = ['B08','B12']
)

B08 = sentinel2_data_cube.band('B08')
B12 = sentinel2_data_cube.band('B12')

ndwi_cube = (B08 - B12) / (B08 + B12)
ndwi_cube.download("ndwi.tif", format = "GTiff")

## value range
img = rasterio.open("ndwi.tif")
[img.read(1).min(), img.read(1).max()]
# [-0.26342073, 0.6292848]


### . scl ----

s2_scl = connection.load_collection(
  "SENTINEL2_L2A_SENTINELHUB"
  , spatial_extent = {'west':5.151836872,'east':5.1533818244,'south':51.181925592,'north':51.184696360,'crs':4326}
  , temporal_extent = ["2020-05-01", "2020-05-10"]
  , bands = ['SCL']
)

mask = s2_scl.band('SCL')
mask = mask != 4

ndwi_cube_masked = ndwi_cube.mask(mask) # .resample_cube_spatial(ndwi_cube)
ndwi_cube_masked.download("ndwi_masked.tif", format = "GTiff")

img1 = rasterio.open("ndwi_masked.tif")

## value range
[np.nanmin(img1.read(1)), np.nanmax(img1.read(1))]
# [-0.06359782, 0.703763]
```

Am I missing something here? At least the spatial extent and resolution of non-masked and masked result are identical..

**Comment by fdetsch** [comment]
Just ran this in a clean session and noticed that the range of values in the masked image changed. However, differences between non-masked and masked output are still evident.

**Comment by soxofaan** [comment]
My first guess (without executing your code) is this problem: Open-EO/openeo-api#349 
When doing gtiff download on VITO backend of a cube covering multiple timestamps, the result is non-deterministic: each time you download the same cube (or a masked version), you might get different values (from different timestamps) for each pixel/subtile.

Could you try with a  smaller time window (containing a single observation), to verify this?

**Comment by fdetsch** [comment]
Argh, yeah.. using `temporal_extent = ["2020-05-02", "2020-05-02"]` gives identical pixel values. Thanks for the help!
