### ISSUE TITLE
problems with UDF (locally)

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-python-client#169]
I tried to execute a UDF locally, as described [in the documentation](https://open-eo.github.io/openeo-python-client/udf.html#example-downloading-a-datacube-and-executing-an-udf-locally), like so:
```
import openeo
from pathlib import Path
from openeo_udf.api.datacube import DataCube

def get_resource(relative_path):
        return str(Path( relative_path))

def load_udf(relative_path):
    import json
    with open(get_resource(relative_path), 'r+') as f:
        return f.read()

smoothing_udf = load_udf("./smooth_savitzky_golay.py")

DataCube.execute_local_udf(smoothing_udf, './evi_cube.nc', fmt='netcdf')
```
Here, I just assumed `from openeo_udf.api.datacube import DataCube` to be the right import, because none is given in the example. It fails with a ModuleNotFoundError: `No module named 'openeo_udf'`. When I try the same with `openeo.rest.datacube` it fails for the same reason. 

What is the correct import in order to use `DataCube` here?

**Comment by soxofaan** [comment]
I think this is related to #159 : openeo-python-client currently depends on openeo_udf (https://github.com/Open-EO/openeo-udf) for that kind of UDF handling. However we want to avoid that extra dependency in a normal install of the openeo python client (see #159)

To work through that example you have to install openeo_udf package manually, but it is not available in the default channels. Something like this should work:

    pip install openeo-udf  --extra-index-url https://artifactory.vgt.vito.be/api/pypi/python-openeo/simple


Also, be careful about importing `DataCube` from the openeo python client and openeo-udf: these are different beasts and should not be mixed.

**Comment by soxofaan** [comment]
part of PR #190  was update to this part of documentation:
```
from openeo.udf import execute_local_udf
execute_local_udf(smoothing_udf, 'test_input.nc', fmt='netcdf')
```

which should fix the issue
