### ISSUE TITLE
Demo server URL not up to date

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-python-client#17]
The [notebook that is linked as "Basic concepts and examples"](https://github.com/Open-EO/openeo-python-client/blob/d531d8f/examples/notebooks/Compositing.ipynb) gives the URL of the demo server as:
http://openeo.vgt.vito.be
But it just returns a 404.

[Elsewhere](https://github.com/Open-EO/openeo-hackathon/blob/99f0d3d5d264bb52668218faa6ec8682dc7c0f5b/test-cases/README.md), I found the link:
http://openeo.vgt.vito.be/openeo
This URL returns:
> OpenEO GeoPyspark backend. /openeo/timeseries

which doesn't make much sense to me, but it's something. Please update the URL.

(Not sure if this should be an issue here or in the geopyspark-driver repo)

**Comment by jdries** [comment]
url is correct in latest version
