### ISSUE TITLE
Document how to run tests

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-python-client#171]
> Is there a way to run the tests locally? I couldn't find details in the docs.

to run the test you need the dev dependencies (from https://github.com/Open-EO/openeo-python-client/blob/master/.travis.yml):

    pip install .[dev]  --extra-index-url https://artifactory.vgt.vito.be/api/pypi/python-openeo/simple

and then you should be able to run the test suite with:

    pytest

We indeed should document this somewhere better

_Originally posted by @soxofaan in https://github.com/Open-EO/openeo-python-client/issues/170#issuecomment-764606827_

**Comment by soxofaan** [comment]
when build finishes: will show up here: https://open-eo.github.io/openeo-python-client/development.html

**Comment by m-mohr** [comment]
Great! I've tried to run it on my machine but got 588 errors unrelated to my changes. I guess that's yet another Windows issue, but not sure...

**Comment by soxofaan** [comment]
you mean a `pytest` run gives you 588 errors? There are indeed 588 tests at the moment. what kind of error messages do you see?

**Comment by m-mohr** [comment]
Yes, it's always something like this:
```
C:\ProgramData\Anaconda3\lib\site-packages\pytest_remotedata\plugin.py:59: AttributeError
____ ERROR at setup of test_aggregate_spatial_read_vector[1.0.0-<lambda>] _____

item = <Function test_aggregate_spatial_read_vector[1.0.0-<lambda>]>

    def pytest_runtest_setup(item):

>       remote_data = item.get_marker('remote_data')
E       AttributeError: 'Function' object has no attribute 'get_marker'

C:\ProgramData\Anaconda3\lib\site-packages\pytest_remotedata\plugin.py:59: AttributeError
========================= 588 error in 14.83 seconds ==========================
```

**Comment by soxofaan** [comment]
That error looks unrelated to openeo code.
You probably have a inconsistency in your python environment. Are you using a fresh dedicated environment for using/dev/testing of openeo python client? Or are you using the default anaconda environment? Using a dedicated/isolated environment is recommended as it minimizes conflicts dependency hell.

I guess it's this `pytest-remotedata` module that is too old. We don't use it in openeo tests, but pytest seems to pick up this plugin automatically.

**Comment by m-mohr** [comment]
I didn't know how to control environments with/for Python until I started Anaconda just now. Now I tried to update the packages (many were outdated), but it is "solving package specifications" for over an hour. So nevermind, this seems to be a local issue. Thanks.
