### ISSUE TITLE
Provide openeo package on conda-forge

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#176]
We provide openeo python client library already on pypi.org, but it could be beneficial to our adoption rate and installation friendliness to also provide it through conda on conda-forge channel.

I'm not sure at the moment what has to happen to make it possible, how much additional maintenance it would require and if it is all worth the trouble. Just putting it out here to collect some feedback, if any.

**Comment by enolfc** [comment]
We do manage most packages with conda in the [EGI Notebooks](https://notebooks.egi.eu) service and having packages in conda would simplify the installation of OpenEO.

**Comment by sebastian-luna-valero** [comment]
Hi,

I am happy to help create a conda package for `openeo-python-client`. Here is the first attempt:
https://github.com/conda-forge/staged-recipes/pull/15717

@soxofaan could you please have a look and provide feedback? Would you like to be included as a conda package maintaner?

Best regards,
Sebastian

**Comment by jdries** [comment]
Hi @sebastian-luna-valero , thanks this is very helpfull, as we don't have experience with this ourselves!
Stefaan is on holiday, so he may not reply for a few weeks.
I had a look at the recipe, looks fine for me. You can add me as a maintainer as well.

**Comment by sebastian-luna-valero** [comment]
Thanks @jdries 

Great, I will add you as a maintainer as well.

I have got `pytest` working on Linux only. Could you have a look at the errors for OSX and Windows [here](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_build/results?buildId=354886&view=logs&jobId=e35d4f76-8ff2-5536-d795-df91e63eb9f7) and let me know your thoughts, please?

Best regards,
Sebastian

**Comment by jdries** [comment]
Hi Sebastian,
seems much needed that we also have some windows and OSX testing.
I'm afraid these point to some actual issues, and seem to remember that they were not super easy to solve.
Is it ok if my colleague Stefaan has a look at this in august? 
Otherwise, we may need to come up with some temporary workaround...

**Comment by sebastian-luna-valero** [comment]
Hi Jeroen,

I am happy to wait until Stefaan can have a look.

It is also possible to just build and release the conda package for Linux, and forget about OSX and Windows for now.

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
Hi,

FYI: I will be on leave the last two weeks of August, so I will be available to help with the conda package either next week or after 31st of August.

Best regards,
Sebastian

**Comment by soxofaan** [comment]
Hi @sebastian-luna-valero thanks for bootstrapping this!  I already had a quick look at conda-forge/staged-recipes#15717

I also did a minor tweak that should hopefully fix the failing tests on osx

**Comment by sebastian-luna-valero** [comment]
Many thanks @soxofaan 

I am now updating the recipe. Let's continue the discussion over there, please.

**Comment by sebastian-luna-valero** [comment]
Hi @soxofaan 

Do you need more time before we continue working on https://github.com/conda-forge/staged-recipes/pull/15717? Or can I add `h5netcdf` back to the list of runtime dependencies?

Best regards,
Sebastian

**Comment by soxofaan** [comment]
hi @sebastian-luna-valero  sorry for the delay.
As noted in conda-forge/staged-recipes#15717  it would be interested to know how you trigger that h5netcdf runtime issue. (We might have to fix that in python client itself, not only the conda recipe)

**Comment by sebastian-luna-valero** [comment]
Hi @soxofaan 

No worries. I added my comments to the `conda-forge` PR.

**Comment by soxofaan** [comment]
FYI: under #198 and #351 ,  windows support was improved and now the test suite should run fully on windows too

**Comment by sebastian-luna-valero** [comment]
Thanks, following up discussion on https://github.com/conda-forge/staged-recipes/pull/15717

**Comment by sebastian-luna-valero** [comment]
Hi @soxofaan 

I see. However, what we added to the conda recipe:
https://github.com/conda-forge/openeo-feedstock/blob/main/recipe/meta.yaml#L25

Is equal to what we have in:
https://github.com/Open-EO/openeo-python-client/blob/master/setup.py#L54

So the differences are due to the dependency resolution made by `conda`/`mamba` vs `pip`.

What would you modify in the conda recipe then?

**Comment by soxofaan** [comment]
@sebastian-luna-valero 
(FYI: I didn't have time to dive into the details yet, I just wanted to quickly mention this here.)
If I understand correctly these additional dependencies are probably secondary side-effects of depending on the conda variants of numpy/pandas/shapely/xarray. Not much we can do then on the level of the openeo recipe.


Another related question:
> ... the conda recipe: https://github.com/conda-forge/openeo-feedstock/blob/main/recipe/meta.yaml#L25
> ... what we have in setup.py:  https://github.com/Open-EO/openeo-python-client/blob/master/setup.py#L54

Do you know approaches or tools to keep these things in sync? Yesterday for example, I added a new test dependency, which eventually should be added to the conda recipy too.


Thanks by the way for pushing this ticket, and apologies it took so long to get all the kinks out.

**Comment by sebastian-luna-valero** [comment]
> Do you know approaches or tools to keep these things in sync?

Sorry, I don't know.

> Thanks by the way for pushing this ticket, and apologies it took so long to get all the kinks out.

No worries, and thanks for your support!

**Comment by soxofaan** [comment]
:+1:  

I think we can close this ticket for now.
Thanks again for all the work

**Comment by soxofaan** [comment]
@sebastian-luna-valero  I just released version 0.15.0 of python client. Can you walk me through the steps required to also get that release in conda-forge?

**Comment by sebastian-luna-valero** [comment]
Hi @soxofaan 

conda-forge automatically opens a PR when a new version of the source code is available: https://github.com/conda-forge/openeo-feedstock/pull/1

Since you are listed as a recipe maintainer you are also notified. It's now up to us to review and merge that PR.

Once the PR is merged, the new conda package will be created and released via the conda-forge channel.
