### ISSUE TITLE
Client sends `float("NaN")` data as `NaN` in JSON

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#185]
If process graph contains `float("NaN")`, client sends this in JSON as `NaN`  which is non-standard extension (aka "invalid").

This is default behavior of json serializing/deserializing in Python, but does not play well with other tools.

We should raise exception or (silently) convert to `null`

**Comment by soxofaan** [comment]
Cleanest solution would be that this is handled in `requests` library automatically, but that is not the case yet: psf/requests#5767

**Comment by soxofaan** [comment]
example issue: a user used `DataCube.mask()` with `replacement=float("nan")`, resulting in invalid JSON in process graph (stored as UDP in VITO backend):

```json
    "mask1": {
      "arguments": {
        "data": {
          "from_node": "loadcollection1"
        },
        "mask": {
          "from_node": "mergecubes1"
        },
        "replacement": NaN
      },
      "process_id": "mask"
    },
```

**Comment by soxofaan** [comment]
psf/requests#5767 was resolved by psf/requests#5810  which will be part of next requests release (>2.25.1) I guess

**Comment by m-mohr** [comment]
By the way, the solution for this issue would be to use the nan process: https://processes.openeo.org/draft/#nan
Replacing it with `null` may not do what the user would expect here.

**Comment by soxofaan** [comment]
> Replacing it with null on the client-side may not do what the user would expect here.

Indeed. Note that silently converting to `null` is not on the table (anymore). The current (but still to be released) solution as provided by the JSON serialization in the `requests` library is to throw an exception.

Using the `nan` process is an alternative. But I think it's best to let the user specify this `nan()` process explicitly in some way. Doing automatic `NaN`-to-`nan()` conversion in the client is far from trivial in practice, and I don't think it's worth to do that.

**Comment by m-mohr** [comment]
That sounds good.

I did not intend to say that an automatic substitution should take place. It could probably be a convenience thing but is really just a nice-to-have. So it's fine that users need to set it explicitly.

**Comment by soxofaan** [comment]
requests 2.26.0 has been released (2021-07-13 according to https://docs.python-requests.org/en/latest/community/updates/)  so that should cover this issue
