### ISSUE TITLE
Drop support for Python 3.5?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#210]
This is a ticket to collect feedback and related tickets/tasks concerning dropping support for Python 3.5 in openeo python client.

Python 3.5 reached end of support in Sept 2020 (first final 3.5.0 release was Sept 2015, final 3.5.10 release was Sept 2020)

Some nice Python3.6 features that could improve and streamline development/maintenance:
- f-strings
- variable annotations (type hints)
- `typing.NamedTuple` with variable annotations makes it easy to create compact containers for openEO data structures
- no more workarounds for usable `tmp_path`  fixture with pytest

**Comment by soxofaan** [comment]
As point of reference, I extracted the client and python versions from the user agents of the openeo-python-client requests made to the VITO production backend during window 2021/05/21 - 2021/06/10 (35k hits):

client version distribution:
```
0.4.4       2130
0.4.8        127
0.6.0        445
0.6.1      25096
0.6.2a1       64
0.7.0       4741
0.7.1a1     3100
```

python version distribution:

```
cpython/3.6.6     14154
cpython/3.6.8      4256
cpython/3.6.9      2371
cpython/3.6.12       30
cpython/3.6.13      414
cpython/3.7.4     10694
cpython/3.7.9         5
cpython/3.7.10      624
cpython/3.8.3       143
cpython/3.8.5      2184
cpython/3.8.8       538
cpython/3.8.10      143
cpython/3.9.2       147
```

Apparently no python 3.5 users in the last 20 days, so that's a good sign.

(To double check that py3.5 users aren't excluded from the data for some reason, I confirmed that the logging works properly by installing openeo in a python:3.5 docker container and connecting to our dev instance)

**Comment by m-mohr** [comment]
The readme already states:

> Requirement: a Python 3.6 (or higher) environment

**Comment by soxofaan** [comment]
indeed, but we are silently still testing on python 3.5: https://github.com/Open-EO/openeo-python-client/blob/921654cab6828aa96450bdb0700be7b47609e45f/.travis.yml#L4

**Comment by soxofaan** [comment]
closing this one, last py3.5-related workarounds are now removed too
