### ISSUE TITLE
Imagery methods: Usabilitiy and User Input

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-python-client#22]
At the  openEO hackathon it came out that users were confused by the functions of the imagecollection. 
They thought that the method calls returns information about the metadata and not applying a process, maybe a process class can help to separate it better.  
In that manner it also came up that it makes sense to return Process classes from "list_processes" instead of just a description.

**Comment by jdries** [comment]
Issue cleaning: ImageCollection is continued for now, it also has some nice features such as easy computations using operator overloading. In general this style can also be found in other libraries, so should not be too uncommon to  a lot of python users.
