### ISSUE TITLE
Handling of fit_curve and predict_curve

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-python-client#222]
I've implemented 3 process graphs using the new processes fit_curve and predict_curve here:
https://github.com/openEOPlatform/SRR2_notebooks/tree/main/UC6_process_graphs

You can get previews of how I'm using `fit_curve` and `predict_curve` here:
https://editor.openeo.org/?server=https://openeo.eurac.edu&discover=1&process=https://raw.githubusercontent.com/openEOPlatform/SRR2_notebooks/main/UC6_process_graphs/UC6_fit.json

https://editor.openeo.org/?server=https://openeo.eurac.edu&discover=1&process=https://raw.githubusercontent.com/openEOPlatform/SRR2_notebooks/main/UC6_process_graphs/UC6_predict.json

I'm trying to replicate the first process graph (UC6_fit.json) where I'm using `fit_curve` using the python client, but I'm having some difficulties defining the fitting function inside it. I've created a sample notebook where I'm trying this:
https://github.com/openEOPlatform/SRR2_notebooks/blob/main/UC6%20-%20Forest%20Dynamics.ipynb

**Comment by jdries** [comment]
This seems to work for me, focusing on how to build the callbacks.
I am using a private function now for the callback in fit_curve, I propose that I also quickly implement support for that function in the client, so it gets cleaner, or do you still have doubts about the signature?

```
## greater than
from openeo.processes import ProcessBuilder, gt
def reducer(x:ProcessBuilder):
    return x.gt(0)
cloud_bands_resampled = cloud_bands_resampled.apply(reducer)

##clip
from openeo.processes import ProcessBuilder, clip
def clipper(x:ProcessBuilder):
    return clip(x,0,4000) #min value was not specified in original?

l2a_bands_masked_clipped = l2a_bands_masked.apply(clipper)

## curve fitting
from openeo.processes import ProcessBuilder, clip, cos, sin, array_element
import math

def fit_function(x:ProcessBuilder,parameters):
    
    pi=math.pi
    a0 = array_element(parameters,0)
    a1 = array_element(parameters,1)
    a2 = array_element(parameters,2)
    return a0 +a1*cos(x*2*pi/31557600) + a2* sin(2*pi/31557600*x)

args_fit_curve= {
    "data": THIS,
    "parameters": [1,1,1],
    "dimension": 't',
    "function": l2a_bands_masked_clipped._get_callback(fit_function, parent_parameters=["data","parameters"])}

curve_fitting = l2a_bands_masked_clipped.process("fit_curve",args_fit_curve)
```

**Comment by clausmichele** [comment]
Thanks! This is a much nicer solution compared to what I was trying.
