### ISSUE TITLE
"Feedback" from code generation

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-python-client#223]
While developing the "code generation" feature in the Web Editor, we found some things that may be considered to be implemented:
- connection.load_collection: Wouldn't it make sense to allow both `id` and `collection_id` as parameters? It would pave the way to deprecate the legacy parameter collection_id at some point.
- If you use datacube.process('reduce_dimension', ...) and pass a function (def xyz: ...) as callback, the function will throw an error as it can't be serialized. That should likely be supported?
- Similarly, I can't use datacube.process('save_result', data = ...) as it complains that data is not allowed.
- There's no way to add metadata to user-defined processes, e.g. adding categories. This is important if you want to share/exchange processes and should be added.

**Comment by soxofaan** [comment]
- connection.load_collection -> #241 
- datacube.process('reduce_dimension', ...) -> #232
- `can't use datacube.process('save_result', data = ...) as it complains that data is not allowed.`  I can not reproduce this, can you elaborate?
- metadata to user-defined processes, e.g. adding categories -> #242

**Comment by m-mohr** [comment]
I can't reproduce the save_result issue any longer, so it might have been fixed in the meantime. As all other issues have separate issues, I'm closing here.
