### ISSUE TITLE
Error Handling: job.download

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-python-client#23]
There should be more error specific information for the job.download() function
e.g.
sending a job with wrong date format --> the download function only returns "{}"

**Comment by bgoesswe** [comment]
In API version 0.0.3 there will be more specific error messages

**Comment by jdries** [comment]
Issue cleaning: error handling has improved a lot, also openeo specific exceptions are thrown.
Bad error messages are logged and resolved case by case.
