### ISSUE TITLE
User feedback on adding a process

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-python-client#24]
During the OenEO hackathon the users wanted to know at least how much data is left if a process like daterange_filter was added. So somehow the user should be able to see if any data gets returned. 
I don't know if this issue should be shifted to the API.

**Comment by m-mohr** [comment]
I think without API changes it would be hard to implement such a feature in the client libraries. Therefore, I opened an issue in the API repo (see above).

**Comment by m-mohr** [comment]
Please try to solve this issue in the Python client using the Subscriptions API for openEO and the topic `openeo.output`. Happy to get feedback in #100 to get this more fleshed out in v0.4.

**Comment by jdries** [comment]
Closing this one, as this is indeed an API issue. Related issue already exists:
https://github.com/Open-EO/openeo-api/issues/243
Note that users do have ways to figure out the result of applying a process, but you have to be creative. For instance using zonal stats is also a good way to figure out at which dates you have relevant data.
Similarly, downloading an image for a small area is a good way to debug your graph, or view the result of applying a process.
