### ISSUE TITLE
UDP storing: add support for  categories, returns, links, ...

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#242]
(from #223)

https://github.com/Open-EO/openeo-python-client/blob/3d62accf61c7c2db017879cace55fb32381a8c32/openeo/rest/udp.py#L63-L75

add support for additional UDP properties: categories, returns, examples, links

**Comment by soxofaan** [comment]
done

**Comment by m-mohr** [comment]
@soxofaan Is there a way to enrich the metadata of a process without storing it? That's what I'm looking for in code generation...

**Comment by soxofaan** [comment]
I'm not sure what you mean, do you have an example/pseudo code what you want to do?

**Comment by m-mohr** [comment]
In JS (and soon in R) I can so something like:

```js
let builder = await connection.buildProcess();

// Set the metadata for the process
builder.description = "# Moisture Stress Index\nCalculate MSI for an area specifying co...";
builder.id = "MSI";
builder.categories = ["foo", "bar"];
builder.summary = "MSI calculation";

let loadcollection1 = builder.load_collection(...);

print(builder.toJSON());
```

Which allows me to print the full metadata with all the additional metadata such as id, summary, categories.

When I was implementing code generation you said that's not possible yet and my hope was that this issue would tackle this... @soxofaan

**Comment by soxofaan** [comment]
there is `openeo.rest.udp.build_process_dict` to simplify building a dictionary with UDP fields
e.g. https://github.com/Open-EO/openeo-python-client/blob/1cc75a3629490ae549fea5e2bf5f18828f212cca/tests/rest/test_udp.py#L440-L459

It requires that you already have a process graph or data cube, but I think that's in your use case

**Comment by m-mohr** [comment]
Thanks, I'll try whether I can make that work.
