### ISSUE TITLE
load_result: Add support for spatial_extent, temporal_extent and bands

### ISSUE THREAD

**Issue by ValentinaHutter** [Open-EO/openeo-python-client#267]
Thanks to @soxofaan additional parameters like `spatial_extent`, `temporal_extent` and `bands` can now be added to the `load_result` process: https://github.com/Open-EO/openeo-python-client/commit/f480815abff0835652917b817b5f739bf0d1882b
I just updated my version of the python client to 0.9.2 to try it out. Unfortunately, I still get the 
`TypeError: load_result() got an unexpected keyword argument 'spatial_extent'`, when I try: 
> spatial_extent  = {'west':11.499,'east':11.501999,'south':46.369,'north':46.373875}
temporal_extent = ["2019-05-10", "2019-06-10"] 
bands           = ["B03","B04"]
testload = connection.load_result(id='jb-28c46f20-288a-4e86-8213-022d8e0416af', spatial_extent=spatial_extent, bands=bands, temporal_extent=temporal_extent)

I am not sure, why this happens, I included the additional parameters in the description of the processes, which you can find here: https://openeo-dev.eodc.eu/v1.0/processes,
(I also added it to https://openeo.eodc.eu/v1.0/processes to test if it would work then) 
and I added the mapping and implementation (but the error appears before these parts are called, so they should not be connected to the error.) 

Does anyone know why this could be? I would really appreciate any hint on that.

**Comment by jdries** [comment]
Easiest approach is to use your python debugger to see if it steps into the expected piece of code with the new feature.
The full stack trace with the location of the typeerror can also help.

**Comment by m-mohr** [comment]
One issue could be that the aggregator doesn't expose the additional parameters yet:
https://docs.openeo.cloud/processes/#load_result
Not sure why...

**Comment by ValentinaHutter** [comment]
Thanks for the great inputs, I will try it again! :) 

I tried it with connecting to the EODC dev, the EODC prod and also with connecting via the aggregator, but the error was returned for every connection. I only included the additional parameters to the prod today, so maybe this update will be in the aggregator by tomorrow. But as I included the parameters to the dev some days ago, this should not be a problem there.

**Comment by soxofaan** [comment]
are you sure you are using ` 0.9.2` ?  
For example, if you are working in a notebook and you update the python package while your notebook is running, you won't get the update. You have to restart your notebook kernel to get package updates.

What does `openeo.client_version()` say (in the environment you are working in)?

**Comment by ValentinaHutter** [comment]
Thank you, I checked again now, and apparently I really did not restart it again correctly, but did not realise it because I only checked the version with !pip freeze which was already on 0.9.2, while openeo.client_version() was not updated yet. Thanks for checking and thanks for all the inputs, it's working now!! :)

**Comment by soxofaan** [comment]
Yeah `!pip freeze `  involves running a new python process  that gets a fresh  view of the situation, while your kernel might still have "outdated" code in code memory

**Comment by ValentinaHutter** [comment]
Thanks again, I was not aware of that yet, but will make sure to check it twice next time! :) Have a good week!
