### ISSUE TITLE
rename_labels for temporal dimension not allowed

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-python-client#274]
I am trying to rename the temporal labels  of a datacube using the python client, but I'm getting the following error:
`MetadataException: Trying to rename labels of dimension DATE of type temporal, which is not supported.`

However, from the process definition there are not limits on which dimension we can use this process https://processes.openeo.org/#rename_labels

@m-mohr can you confirm that the rename_labels process can be used also for the temporal dimension?

**Comment by m-mohr** [comment]
Should be possible. If the provider doesn't support non-temporal labels for temporal dimensions the dimension type should probably change (to "other" or so).
