### ISSUE TITLE
UDF context option represented in python client

### ISSUE THREAD

**Issue by Jaapel** [Open-EO/openeo-python-client#291]
Supplying user variables in a UDF is performed via a context argument.
For [vector cubes](https://open-eo.github.io/openeo-python-client/_modules/openeo/rest/vectorcube.html#VectorCube.run_udf), this is implemented since version 0.10. 

How can I supply context for a normal UDF with the python client (for example in [apply dimension](https://open-eo.github.io/openeo-python-client/api.html?highlight=apply_dimension#openeo.rest.datacube.DataCube.apply_dimension))?

**Comment by soxofaan** [comment]
in a86a20d I added `context` argument to `DataCube.apply_dimension`.

If you're stuck with a version of the client that's not recent enough yet (release 0.10.0 or lower), you can workaround it as follows:

```python
cube = cube.apply_dimension( ....)
cube._pg.arguments["context"] = {"foo": 867}
```
