### ISSUE TITLE
openeo-python-client/tests/test_bandmath.py

### ISSUE THREAD

**Issue by ms801221** [Open-EO/openeo-python-client#3]
Thoughts to create time series of single point:

1. imagecollection.filter('x_coord == 21 AND y_coord==57'); result should stay an imagecollection; for now no dimension reduction
2. imagecollection.reduction(...); definition, which dimensions should be kept; result should become different class as pointcollection, if appropriate.

**Comment by jdries** [comment]
Closing issue, point filtering/timeseries is discussed in: https://github.com/Open-EO/openeo-processes/issues/37
