### ISSUE TITLE
Clean up temp OIDC token workaround for EURAC backend

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#300]
https://github.com/Open-EO/openeo-python-client/blob/cb4aadc0191cb9c02b9b40f7034f7c550eac75e1/openeo/rest/connection.py#L215-L218

see https://github.com/Open-EO/openeo-wcps-driver/issues/45

**Comment by clausmichele** [comment]
Nice, I've also just bumped into this looking into the code and verified that now the EURAC back-end works fine with the access_token! Only later I've found this PR.
