### ISSUE TITLE
deprecated `distutils.version.LooseVersion`

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#316]
Noticed this in test warnings
```
tests/test_views_execute.py: 24 warnings
  /../openeo/openeo-python-client/openeo/capabilities.py:85: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    self._version = LooseVersion(version)
```

**Comment by soxofaan** [comment]
see https://github.com/pypa/distutils/pull/75

**Comment by soxofaan** [comment]
migrating to this `packaging` package means adding a new dependency, which we want to avoid if not necessary.
In this case it's probably not hard to  replace it with a DIY implementation (split version string in tuple of ints and use standard tuple comparison functionality)

**Comment by iamkaushal** [comment]
@soxofaan I have created a PR for this issue. Please review it, this is my first open source contribution.

**Comment by soxofaan** [comment]
#321  was merged
