### ISSUE TITLE
Adding error handling to user file handling

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-python-client#32]
Error handling to user file upload / download / deletion should be improved by adding exceptions, and more relevant return values than true or false.

**Comment by jdries** [comment]
Note that user file handling is mainly unimplemented, also in backends. So all of the api will probably needs revisioning.

**Comment by soxofaan** [comment]
Also, since b4f2de and ee50d0, errors returned by the API (status > 400) are automatically converted to python exceptions by default now, so I don't think it is useful to keep this issue open
