### ISSUE TITLE
Less verbose log printing on failed batch job

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#332]
https://github.com/Open-EO/openeo-python-client/blob/a184da6354323c21338e8cab7533bd927e8fc1e5/openeo/rest/job.py#L226-L235

This automatic log printing when a batch job failed  is currently very verbose (up to debug level).
I have notebooks with failed jobs that have thousands of lines of this log dumping. That's not very practical to work with (e.g. copy-paste it to the support forum)

I guess we  should only show warn and error level by default, and show instructions to get more detailed logs

**Comment by soxofaan** [comment]
@jdries what do you think?

**Comment by jdries** [comment]
Indeed, filtering on even only 'ERROR' logs would make more sense.

**Comment by soxofaan** [comment]
merged #374
