### ISSUE TITLE
Jupyter integration: Visualization for DataCube

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-python-client#336]
We should try to show the Model Builder output instead of the class name:

![image](https://user-images.githubusercontent.com/8262166/196707777-3a2825db-15f5-4037-a0bd-f2ba6aeee0e7.png)

I thought we would already have this, but may only work for batch jobs?

**Comment by soxofaan** [comment]
I think we only do that with batch jobs for now indeed.

makes sense to also do that with `DataCube` and related constructs

**Comment by m-mohr** [comment]
What other constructs would that be?

**Comment by soxofaan** [comment]
`VectorCube` and `MlModel`  (subclasses of `_ProcessGraphAbstraction`)
