### ISSUE TITLE
Windows compatibility: unit test about configuration fail

### ISSUE THREAD

**Issue by JohanKJSchreurs** [Open-EO/openeo-python-client#350]
Some unit tests fail on Windows. They seem to be related to configuration files and where they are located.

At first sight, the tests seem to make some assumptions, such as some default paths and that the path separator is / .
So it might just be that for these 3 tests, it it is only the test that needs to be fixed.

This is the test summary:

```
============================================================= short test summary info =============================================================
FAILED tests/test_config.py::test_get_user_config_dir - AssertionError: assert WindowsPath('C:/Users/testuser/AppData/Roaming/openeo-python-client') == (WindowsPath('C:/dev-projects/VITO/codebases/ope...
FAILED tests/test_config.py::test_get_user_data_dir - AssertionError: assert WindowsPath('C:/Users/testuser/AppData/Roaming/openeo-python-client') == (WindowsPath('C:/dev-projects/VITO/codebases/ope...
FAILED tests/rest/auth/test_cli.py::test_paths - AssertionError: assert '/auth-config.json' in 'openEO auth config: C:\\Users\\testuser\\AppData\\Local\\Temp\\pytest-of-testuser\\pytest-52\\test...
============================================ 3 failed, 1260 passed, 17 skipped, 179 warnings in 55.49s ============================================
```

**Comment by soxofaan** [comment]
FYI:  this bit of conftest is probably important here:
https://github.com/Open-EO/openeo-python-client/blob/01f525615fead0db67810fc2f1b92f4e15b7a089/tests/conftest.py#L11-L13

it sets up some "home dir" related env vars that probably only work on linux

**Comment by soxofaan** [comment]
PR  #354 was merged
