### ISSUE TITLE
Package on Conda?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-python-client#372]
During the ESIP meeting a participant said that it would be nice to have the Python client (and maybe also R) available through Conda in addition to pip.

**Comment by m-mohr** [comment]
Also something that would avoid issues like https://discuss.eodc.eu/t/how-to-get-imagery-footprint-and-filter-by-cloud-coverage/551/5

**Comment by soxofaan** [comment]
This is already being worked on:
-  #176 
- https://github.com/conda-forge/staged-recipes/pull/15717

**Comment by soxofaan** [comment]
FYI: openeo package is now available on conda forge: https://anaconda.org/conda-forge/openeo

**Comment by m-mohr** [comment]
@soxofaan Thanks, great work. I've added the link to openeo.org, docs.openeo.cloud etc. For example directly here: https://openeo.org
