### ISSUE TITLE
Incomplete /files support?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-python-client#377]
It seems the Python client supports `GET /files` to list all user-uploaded files, but I can't find any information about the other file-related endpoints. How can users upload/download and delete files?

**Comment by soxofaan** [comment]
indeed, file support in python client is very limited atm

**Comment by soxofaan** [comment]
(rebase+) merged #378  in d16417c98290c98ffea0efc4b463374ed9ea6b14
