### ISSUE TITLE
`DataCube.aggregate_spatial` should return a vector cube

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#386]
`DataCube.aggregate_spatial` currently returns a (raster) `DataCube`:

https://github.com/Open-EO/openeo-python-client/blob/c590db2f796fa92466e4bda08e9938d8453069ff/openeo/rest/datacube.py#L962-L997

but it should actually return a vector cube.

Changing this should be easy, but I'm unsure if this would cause some trouble down the line in usecases that depend on the current implementation (of returning a DataCube object)

**Comment by jdries** [comment]
I would change it. The only use case I can think of is running a udf on the result of aggregate_spatial, so if our new vector cube has the same methods for that, we should be fine?

**Comment by soxofaan** [comment]
I indeed started with a PR (#389). I'm already touching more code than I anticipated, and I still have failing tests

**Comment by soxofaan** [comment]
done

> The only use case I can think of is running a udf on the result of aggregate_spatial, so if our new vector cube has the same methods for that, we should be fine?

Indeed. That's actually even being improved in #385 / #388
