### ISSUE TITLE
openeo-python-client/openeo/catalog.py

### ISSUE THREAD

**Issue by ms801221** [Open-EO/openeo-python-client#4]
Suggestions for needed parameters and their retrieval methods within an EO product:

- data level
   - NASA's definition would be a standard, see https://eospso.gsfc.nasa.gov/sites/default/files/publications/2006ReferenceHandbook.pdf, p. 31
 -  NaN value
 - range / type of values
 - owner / copyright notice
 - ?? producer's product description (if level 1-4) ??

**Comment by jdries** [comment]
Issue cleanup: this is actually an API suggestion, which again depends on STAC. Most of the suggestions are probably supported there.
