### ISSUE TITLE
Automatically validate a process graph before download/execute/execute_batch, ...

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#404]
The `/validation` endpoint allows back-end to run some pre-flight checks on a process graph without executing it. This should give quick feedback about the validity of a given process graph, not only in syntactic sense, but also in sense of data availability, or "too large extent" checks.

Doing `/validation` check automatically (with option to disable it) from `.download()`, `.create_job()`, `.execute_batch()`, ... might be interesting to give quicker feedback to user

**Comment by jdries** [comment]
Step 1: log warning but still submit job, this avoids blocking jobs when /validation endpoint doesn't work properly.

**Comment by soxofaan** [comment]
merged PR #481 in 78e8e939d77d63a9cd699c8861e648dda29c905b
