### ISSUE TITLE
Running setup.py on macos x - 

### ISSUE THREAD

**Issue by jwagemann** [Open-EO/openeo-python-client#41]
When running the setup.py with pip install --user -e ., I get 'unknown option: test_requirements'.
I am on a macOS High Sierra. Working on a Python3.7 virtual environment.

See complete error message below. Setup_tools is installed.

Installing collected packages: openeo-api
  Running setup.py develop for openeo-api
    Complete output from command /.virtualenvs/myvenv/bin/python3.7 -c "import setuptools, tokenize;__file__='/Documents/Notebooks/bed_services/openeo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=:
    /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'test_requirements'
      warnings.warn(msg)
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --user not recognized
    
    ----------------------------------------
Command "/.virtualenvs/myvenv/bin/python3.7 -c "import setuptools, tokenize;__file__='/Documents/Notebooks/bed_services/openeo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=" failed with error code 1 in /Documents/Notebooks/bed_services/openeo/

**Comment by bgoesswe** [comment]
I think the --user option is not available anymore, if you run it without it it should work. 
So just "pip install -e"

**Comment by jwagemann** [comment]
Great it worked. Would be great if you could update your README.md. Thanks!
