### ISSUE TITLE
Error in HTML representation of job if billing info is missing

### ISSUE THREAD

**Issue by LukeWeidenwalker** [Open-EO/openeo-python-client#414]
According to [the docs](https://openeo.org/documentation/1.0/developers/api/reference.html#tag/Capabilities/operation/capabilities), billing information is optional in capabilities. However, when this is returned as `null` (as is currently the case in our dev-backend), the client will throw an exception when attempting to load the HTML representation of a job (e.g. in jupyter), because `conn.capabilities()` will return `None`, which doesn't have the `.get()` method. We'll ofc fix this on our end too, but might want to catch this error in the client too if the endpoint is indeed optional!

--- 

```
>>> job
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/repos/eodc-api/openeo-integration-tests/.venv/lib/python3.10/site-packages/IPython/core/formatters.py:344, in BaseFormatter.__call__(self, obj)
    342     method = get_real_method(obj, self.print_method)
    343     if method is not None:
--> 344         return method()
    345     return None
    346 else:

File ~/repos/eodc-api/openeo-integration-tests/.venv/lib/python3.10/site-packages/openeo/rest/job.py:47, in BatchJob._repr_html_(self)
     45 def _repr_html_(self):
     46     data = self.describe_job()
---> 47     currency = self.connection.capabilities().currency()
     48     return render_component('job', data=data, parameters={'currency': currency})

File ~/repos/eodc-api/openeo-integration-tests/.venv/lib/python3.10/site-packages/openeo/rest/rest_capabilities.py:41, in RESTCapabilities.currency(self)
     39 def currency(self):
     40     """ Get default billing currency."""
---> 41     return self.capabilities.get('billing', {}).get('currency')

AttributeError: 'NoneType' object has no attribute 'get'
<BatchJob job_id='ce50bca7-7be0-4538-8a62-61fb1e743f0e'>
```

**Comment by soxofaan** [comment]
That can be addressed easily  in the client.

However, I don't think it is allowed to set "billing" explicitly to "null". You can omit the whole field, but if you set it, it must at least be an object (with "currency" field)
