### ISSUE TITLE
MultibackendJobManager: stop when finished

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-python-client#432]
when all jobs are processed, script should finish instead of remaining in infinite loop

**Comment by soxofaan** [comment]
is that because status "error" is missing from 
https://github.com/Open-EO/openeo-python-client/blob/2b8914c4ff2394bffbb1ec25cb3f906076fa44a6/openeo/extra/job_management.py#L254-L261 ?

**Comment by jdries** [comment]
seems likely
