### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#438]
Some quick todo's, action points to improve the README and make it more attractive

- drop Quick Start Guide link to openeo.org docs, everything should be in own docs by now
- finetune how we link to own docs (eliminate duplication)
- is it still necessary to point windows users to anaconda for shapely?
- add example snippet + screenshot like on https://open-eo.github.io/openeo-python-client/#

**Comment by soxofaan** [comment]
> is it still necessary to point windows users to anaconda for shapely?

@JohanKJSchreurs can you verify if anaconda is still required/recommended to install shapely on windows, or does a simple vanilla `venv` + `pip`  also work nowadays?

**Comment by soxofaan** [comment]
great, that allows to clean up some of that ugly workaround cruft.


@clausmichele  you probably also have experience with these kind of packages on Windows: do you know about particular installation issues nowadays?

**Comment by soxofaan** [comment]
what environment solution(s) do you use? stdlib venv+pip, virtualenv+pip, conda, something else, ...?

**Comment by clausmichele** [comment]
Usually conda, now I also tried venv + pip with a fresh env with Python 3.9.15 and the installation went fine:

```
Successfully built openeo
Installing collected packages: sortedcontainers, pywin32, pytz, msgpack, zipp, zict, wrapt, urllib3, tzdata, typing-extensions, tornado, toolz, tblib, six, pyyaml, pytzdata, pyparsing, psutil, packaging, oschmod, openeo-processes-dask, numpy, networkx, MarkupSafe, locket, idna, fsspec, colorama, cloudpickle, charset-normalizer, certifi, cachetools, attrs, affine, snuggs, shapely, requests, python-dateutil, pyproj, pydantic, partd, jinja2, importlib-metadata, deprecated, click, pendulum, pandas, odc-geo, geojson-pydantic, dask, cligj, click-plugins, xarray, rasterio, openeo-pg-parser-networkx, fiona, distributed, rioxarray, openeo, geopandas, dask-geopandas
Successfully installed MarkupSafe-2.1.3 affine-2.4.0 attrs-23.1.0 cachetools-5.3.1 certifi-2023.5.7 charset-normalizer-3.1.0 click-8.1.3 click-plugins-1.1.1 cligj-0.7.2 cloudpickle-2.2.1 colorama-0.4.6 dask-2023.6.0 dask-geopandas-0.3.1 deprecated-1.2.14 distributed-2023.6.0 fiona-1.9.4.post1 fsspec-2023.6.0 geojson-pydantic-0.5.0 geopandas-0.13.2 idna-3.4 importlib-metadata-6.6.0 jinja2-3.1.2 locket-1.0.0 msgpack-1.0.5 networkx-2.8.8 numpy-1.24.3 odc-geo-0.3.3 openeo-0.19.0a1 openeo-pg-parser-networkx-2023.5.1 openeo-processes-dask-2023.5.1 oschmod-0.3.12 packaging-23.1 pandas-2.0.2 partd-1.4.0 pendulum-2.1.2 psutil-5.9.5 pydantic-1.10.9 pyparsing-3.0.9 pyproj-3.6.0 python-dateutil-2.8.2 pytz-2023.3 pytzdata-2020.1 pywin32-306 pyyaml-6.0 rasterio-1.3.7 requests-2.31.0 rioxarray-0.14.1 shapely-2.0.1 six-1.16.0 snuggs-1.4.7 sortedcontainers-2.4.0 tblib-1.7.0 toolz-0.12.0 tornado-6.3.2 typing-extensions-4.6.3 tzdata-2023.3 urllib3-2.0.3 wrapt-1.15.0 xarray-2023.5.0 zict-3.0.0 zipp-3.15.0
```

**Comment by soxofaan** [comment]
seems all points mentioned here are already handled by now, so closing
