### ISSUE TITLE
open auth URL in new window

### ISSUE THREAD

**Issue by dthiex** [Open-EO/openeo-python-client#443]
Could we change the client that the Visit Link to authenticate would open in a new window. It's a bit annoying that when you want to open it to authenticate the browser tries to leave the notebook. 

![image](https://github.com/Open-EO/openeo-python-client/assets/60705209/6f2389ea-38a3-413d-8d1c-7c169680d978)

**Comment by soxofaan** [comment]
hmm, for me it already opens the link in a new tab (using jupyterlab 4.0.2 here)
what notebook environment do you use?

**Comment by soxofaan** [comment]
anyway 2b8914c should do the trick I guess

**Comment by dthiex** [comment]
> anyway https://github.com/Open-EO/openeo-python-client/commit/2b8914c4ff2394bffbb1ec25cb3f906076fa44a6 should do the trick I guess

Indeed works now, thanks! (I was on jupyter ==1.0.0 and notebook ==6.5.4 while testing this).
