### ISSUE TITLE
Include openeo vue component version info in `openeo.client_version`

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#444]
idea from https://github.com/Open-EO/openeo-vue-components/issues/93:

include version information about jupyter openep vue components in `openeo.client_version()` output.

Now it's just a string, but we could make it a richer object that renders additional version info in a jupyter context.

![Screenshot from 2023-06-19 17-38-06](https://github.com/Open-EO/openeo-python-client/assets/44946/5ecaf261-7401-48de-9005-103ae23fa99e)

**Comment by m-mohr** [comment]
That's not possible as we simply include the latest 2.x version from a CDN, which decides for us which version to import.

**Comment by soxofaan** [comment]
yes I understand that this is not possible from Python side, but doesn't the running JS code know its own version?

I was thinking along the lines to make  `openeo.client_version().__repr__()`  include some javascript snippet to render its own version (in "javascript space")

**Comment by m-mohr** [comment]
No, the JS code doesn't know its version number right now.

**Comment by soxofaan** [comment]
ah ok, I assumed this would be a relatively low hanging fruit thing.

will close this feature request for now, it's not that important to have in general anyway
