### ISSUE TITLE
CSV downloaded with synchronous "download" gives JSON-structured output

### ISSUE THREAD

**Issue by Pratichhya** [Open-EO/openeo-python-client#449]
When downloading a csv file using a synchronous approach. It returns data in JSON format. 

Performed: `cube.download("my_result.csv")`

Resulted output sample in a csv file: 

> {"2020-06-01T00:00:00Z":[[0.748832450333613],[0.4964776563741113],[0.6570071710833252],[0.4878170884663786]],"2020-06-04T00:00:00Z":[[0.0230362131024838],[0.0210558454592638],[0.020667860950573],[0.0214809115294978]],"2020-06-06T00:00:00Z":[[0.7757732911277135],[0.5010382193731348],[0.719923551958639],[0.3880461017364886]],"2020-06-09T00:00:00Z":[[0.0369665531354938],[0.0385640003326478],[0.031821943594066],[0.019730403069427]]}

**Comment by soxofaan** [comment]
already fixed this for `VectorCube.download`.

Still to do for `VectorCube.execute_batch`
