### ISSUE TITLE
Exception "Missing schema" on download_results()

### ISSUE THREAD

**Issue by Sijoma** [Open-EO/openeo-python-client#45]
I have a loop that fetches results from e.g GEE and EURAC, but it somehow does not work when using EURAC.

I am getting the following exception after around a minute of waiting:

requests.exceptions.MissingSchema: Invalid URL '/jobs/781ddbd4-306f-48c2-9a2f-8cd387a18c5b/results': No schema supplied. Perhaps you meant http:///jobs/781ddbd4-306f-48c2-9a2f-8cd387a18c5b/results?

Backend url: http://saocompute.eurac.edu/openEO_0_3_0/openeo
Process graph:
```json
{
  "min": -1,
  "max": 1,
  "imagery": {
    "imagery": {
      "red": "B04",
      "nir": "B08",
      "imagery": {
        "extent": [
          "2018-06-04T00:00:00Z",
          "2018-06-04T23:59:59Z"
        ],
        "imagery": {
          "extent": {
            "west": 8.71,
            "south": 47,
            "east": 9.8,
            "north": 47.8
          },
          "imagery": {
            "process_id": "get_collection",
            "name": "openEO_S2_32632_10m_L2A"
          },
          "process_id": "filter_bbox"
        },
        "process_id": "filter_daterange"
      },
      "process_id": "NDVI"
    },
    "process_id": "min_time"
  },
  "process_id": "stretch_colors"
}
```

Using the synchronous way with .download() also does not work. But this may be due to the fact that the function is deprecated?

AttributeError: 'RESTConnection' object has no attribute 'download_job'

**Comment by Sijoma** [comment]
I think it has something to do with the output_format. It seems the format is currently not used when creating a process graph?

![image](https://user-images.githubusercontent.com/8970764/56427111-ed870a00-62ba-11e9-848b-790bdb5358d4.png)

**Comment by Sijoma** [comment]
Additionally, I think EURAC may not be fully compliant as they immediately return the image under the link jobs/:id/results. However, the openeo-python-client expects a JSON response, which matches the API reference.

**Comment by jdries** [comment]
Closing old issue: Eurac <-> python client compatibility has been improved
