### ISSUE TITLE
Drop support for python 3.6

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#460]
Keeping python 3.6 support starts slowing down development (just had another test failing due to feature not available on 3.6)

python 3.6 is end of life since dec 2021 and python 3.7 is available for more than 5 years (june 2018).

Time to stop supporting 3.6 I'd say

**Comment by jdries** [comment]
fine for me, go ahead!

**Comment by soxofaan** [comment]
Note to self: some interesting [3.7+ features](https://docs.python.org/3/whatsnew/3.7.html) that will be unlocked:

- [PEP 563 postponed evaluation of type annotations](https://docs.python.org/3/whatsnew/3.7.html#pep-563-postponed-evaluation-of-annotations)  (avoid need to specify return "self" type as string)
- [dataclasses](https://docs.python.org/3/library/dataclasses.html#module-dataclasses): [PEP 557 – Data Classes](https://docs.python.org/3/whatsnew/3.7.html#whatsnew37-pep557): cleaner, more expressive API than namedtuples
- [importlib.resources](https://docs.python.org/3/whatsnew/3.7.html#whatsnew37-importlib-resources) replacement for deprecated pkg_resources

**Comment by soxofaan** [comment]
done
