### ISSUE TITLE
cleanup load_disk_collection/load_disk_data/load_uploaded_files

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#467]
https://github.com/Open-EO/openeo-python-client/blob/fd6d9f648ba3074725baa57fca9e70cfa090e555/openeo/rest/datacube.py#L203-L218

This `Connection` method is called `load_disk_collection`, while used openeo process is called `load_disk_data`.
Neither of these is an official process.

Closest matching standard openeo process is `load_uploaded_files`, which does not have a related `Connection` method in python client. (`vectorcube_from_paths` uses it, but that's again another name).

Clearly some room for improvement/cleanup

**Comment by jdries** [comment]
I marked load_disk_collection as deprecated in favour of load_stac.
