### ISSUE TITLE
DataCube' object has no attribute 'graph'

### ISSUE THREAD

**Issue by tetaud-sebastien** [Open-EO/openeo-python-client#473]
AttributeError: 'DataCube' object has no attribute 'graph'

**Comment by soxofaan** [comment]
Can you provide more context about how/when this is happening and what you are trying to do?

**Comment by soxofaan** [comment]
Note that a recent enough version of the openeo python client does not any contain `cube.graph` usage (anymore), so there is likely a bug in your own code.

**Comment by clausmichele** [comment]
If you want to obtain the process graph you can instead do:

`cube.print_json()`

**Comment by jdries** [comment]
No response, please reopen if still relevant.
