### ISSUE TITLE
Basic authentication with hub

### ISSUE THREAD

**Issue by josepsitjar** [Open-EO/openeo-python-client#487]
When I try to implement the basic authentication to connect with a hub like 'Earth Engine' or 'Copernicus Data Space Ecosystem', it throws an error:
OpenEoApiError: [403] CredentialsInvalid: Credentials are not correct

The credentials are correct, and I can connect with them through the authenticate_oidc method, or also with the EO web editor. 

Any suggestion?
Thanks in advance.

**Comment by soxofaan** [comment]
You can not use your OIDC credentials with basic authentication. Basic auth uses a completely different  credentials system.  Moreover, basic auth should be avoided for general usage, and most openEO back-ends even don't support it
