### ISSUE TITLE
Parsing of timeseries data

### ISSUE THREAD

**Issue by GreatEmerald** [Open-EO/openeo-python-client#5]
The client could parse timeseries data directly into a Pandas DataFrame, instead of requiring the user to do so manually.

This relates to https://github.com/Open-EO/openeo-api/issues/46 - more metadata is needed to know that the response is in fact something that can be parsed into one.

**Comment by jdries** [comment]
This exists now:
openeo.rest.conversions.timeseries_json_to_pandas
