### ISSUE TITLE
test_bandmath.py randomly fails on python 3.5

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#50]
When running the unit tests from test_bandmath.py on python 3.5 you randomly get:
- no failure
- failure in test_evi:

      self.assertDictEqual(expected_graph,actual_graph)
      E       AssertionError: {'red[578 chars]ex': 2, 'data': {'from_argument': 'data'}}, 'r[1423 chars]lse}} != {'red[578 chars]ex': 1, 'data': {'from_argument': 'data'}}, 'r[1423 chars]lse}}

- failure in test_evi:

      tests/test_bandmath.py:50:
      >  evi_cube = (2.5 * (B08 - B04)) / ((B08 + 6.0 * B04 - 7.5 * B02) + 1.0)
      openeo/rest/imagecollectionclient.py:264: in __sub__
           return self.subtract(other)
      openeo/rest/imagecollectionclient.py:151: in subtract
           return self._reduce_bands_binary(operator, other)
           >           input1_id = list(merged.processes.keys())[list(merged.processes.values()).index(input1)]
           E           ValueError: {'result': True, 'arguments': {'data': [{'from_node': 'arrayelement2'}, {'from_node': 'product1'}]}, 'process_id': 'sum'} is not in list

**Comment by soxofaan** [comment]
I did some debugging already and the reason for this random failing is because of the dictionary item order issues. Since python 3.6 dictionary items are ordered based on insertion, but this in only a implementation (since 3.7 it is an official feature). In python 3.5 dict item order is not deterministic, which plays bad with the merging logic in `GraphBuilder` and `ImageCollectionClient._reduce_bands_binary`

**Comment by jdries** [comment]
Think this is solved!
