### ISSUE TITLE
docs: add logging for multi backend job manager

### ISSUE THREAD

**Issue by JanssenBrm** [Open-EO/openeo-python-client#517]
The Python client supports the usage of the multi backend job manager (https://open-eo.github.io/openeo-python-client/cookbook/job_manager.html). However, when executing the code that is available on the page, the user doesn't get much logging and it is difficult to monitor if anything is happening, except for looking at the CSV file. It could be interesting to add some more information on how to enable logging for the job manager.

**Comment by soxofaan** [comment]
done by #518
