### ISSUE TITLE
No metadata for datacube loaded with `load_stac`

### ISSUE THREAD

**Issue by VincentVerelst** [Open-EO/openeo-python-client#527]
Datacubes that are loaded from a STAC catalog using `load_stac` don't contain any metadata.

**Comment by soxofaan** [comment]
related to https://github.com/Open-EO/openeo-python-client/issues/464 and https://github.com/Open-EO/openeo-python-client/issues/425

**Comment by jdries** [comment]
This is also a duplicate of:
https://github.com/Open-EO/openeo-python-client/issues/368
We'll probably just want to clearly deprecate load_result, so that we only have to fix this one.

**Comment by soxofaan** [comment]
FYI: `load_result` is a non-experimental process in openeo-processes 1.0.0 (it moved to "proposals" in 1.1.0), so strictly speaking we can not easily deprecate it in general. But I agree that we probably should not bother (bug)fixing it.

**Comment by VincentVerelst** [comment]
TODO: add unit testing
