### ISSUE TITLE
Pylance type check is not working

### ISSUE THREAD

**Issue by hoetmaaiers** [Open-EO/openeo-python-client#542]
The load_connection function in VSCode returns me the types of the decorator. This can be solved by changing the type signature of the `openeo_process`.

Changing the current implementation https://github.com/Open-EO/openeo-python-client/blob/master/openeo/internal/documentation.py#L14

to this solves that problem:

```python
T = TypeVar('T')

def openeo_process(f: Optional[T] = None, process_id: Optional[str] = None, mode: Optional[str] = None) -> T:
```

Does this make sense to the OpenEO contributors? Is a PR a good idea for this?

@hghcomphys helped me figuring out this problem 🙏

**Comment by soxofaan** [comment]
Sure, if this is something that improves the developer experience, we would be certainly open to something like this.

**Comment by soxofaan** [comment]
done with #543 
thanks!
