### ISSUE TITLE
load_stac: get asset metadata from "item_assets" in collection instead of from items

### ISSUE THREAD

**Issue by VictorVerhaert** [Open-EO/openeo-python-client#553]
Right now asset metadata like band names are loaded from the nested items in a collection. Getting them directly from item_assets could improve performance.

This would also serve as a quick fix for https://github.com/Open-EO/openeo-geopyspark-driver/issues/460

**Comment by soxofaan** [comment]
are you referring here to https://github.com/Open-EO/openeo-python-client/blob/59655b8c16f468c751c4381a29e99674f58be344/openeo/metadata.py#L564-L576  in particular  or is this about something else?

**Comment by VictorVerhaert** [comment]
Yeah initialy we were talking about the python driver, but this turned out to be useless as each items needs to be checked anyway.

@VincentVerelst mentioned that this could however improve performance for the python client for his use case (GFMap?) so this issue was transferred to the python client.

**Comment by VincentVerelst** [comment]
Indeed, in case that the item_asset extension in present in the STAC collection, we can read the band names from there and don't need to iterate over each item in the collection.

**Comment by soxofaan** [comment]
I think this is already covered by #577 
(feel free to reopen if not)
