### ISSUE TITLE
Add method to load the results of a previous job

### ISSUE THREAD

**Issue by VictorVerhaert** [Open-EO/openeo-python-client#566]
Add a method to the openeo python client to directly load the result of a previous job. The python client in turn fetches the stac of the previous job and add a `load_stac` with this link to the PG.

The method should receive either a `Job` object of a job-id as argument.

**Comment by soxofaan** [comment]
suggestion: use the method name `load_stac_from_job`, which is self-explaining a easy to discover (e.g will automatically be suggested by autocomplete functionality if you start typing "load_stac")
