### ISSUE TITLE
JobManager: store joblist on http url as Parquet

### ISSUE THREAD

**Issue by VincentVerelst** [Open-EO/openeo-python-client#571]
https://github.com/Open-EO/openeo-gfmap/issues/107

- [x] Support Parquet
- [x] Support URL

**Comment by VincentVerelst** [comment]
@soxofaan , I've made a gist on how I'd implement URL support in the MultiBackendJobManager: https://gist.github.com/VincentVerelst/aef96f03b5b45a3506d8945730af8221
It would require a user to always provide a url_read_write_helper if they provide a URL. We could foresee maybe some default helpers for CSV and Parquet on Artifactory?

Could you already have a look and leave your comments, before I start the full implementation?

**Comment by soxofaan** [comment]
As a next step I was more thinking like PR #595
