### ISSUE TITLE
`metadata_from_stac` can't handle STAC API ItemCollection

### ISSUE THREAD

**Issue by VincentVerelst** [Open-EO/openeo-python-client#573]
When trying to read metadata from a STAC API (e.g. https://stac.openeo.vito.be/collections/agera5_daily), `metadata_from_stac` is not able to read metadata from a STAC API ItemCollection (https://github.com/radiantearth/stac-api-spec/blob/release/v1.0.0/fragments/itemcollection/README.md)

**Comment by soxofaan** [comment]
client now parses band info from https://stac.openeo.vito.be/collections/agera5_daily (item_assets field)

I think I'll close this one. Feel free to reopen or start a new ticket for other cases
