### ISSUE TITLE
As a developer I want to provide the MultiBackendJobManager with a maximal run time for each job.

### ISSUE THREAD

**Issue by HansVRP** [Open-EO/openeo-python-client#590]
Currently the MultiBackendJobManager, and batch jobs by extension to o not have a 'failsave' to avoid extremely expensive jobs. 

What I propose is to measure the time how long a job is in running, and provide an input parameter to cancel the job in case it goes over the predicted runtime.

**Comment by soxofaan** [comment]
I think this ticket is done (with #596) and can be closed
