### ISSUE TITLE
github project name versus pip name versus package name

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#60]
The git/github level name of this project is "openeo-python-client" (https://github.com/Open-EO/openeo-python-client)

When installing/building the package the name "openeo-api" / "openeo_api" is used. e.g.:

    $ docker run --rm -it -w/app python bash
    # git clone https://github.com/Open-EO/openeo-python-client.git
    # cd openeo-python-client/
    # pip install -r requirements.txt
    ....
    # pip install -e .
    ...
    Installing collected packages: openeo-api
      Running setup.py develop for openeo-api
    Successfully installed openeo-api

    # pip freeze | grep openeo
    -e git+https://github.com/Open-EO/openeo-python-client.git@..#egg=openeo_api

This is pretty confusing, especially because there is a related project with that openeo-api name: https://github.com/Open-EO/openeo-api

Morever, to use it, one has to use the name "openeo":

    # python
    >>> import openeo
    >>> openeo
    <module 'openeo' from '/usr/local/lib/python3.7/site-packages/openeo/__init__.py'>

**Comment by soxofaan** [comment]
(background: I was looking into the geopyspark driver deps and got confused: https://github.com/Open-EO/openeo-geopyspark-driver/blob/master/requirements.txt#L9)

**Comment by jdries** [comment]
Perhaps we can simply rename the python package to 'openeo'.
The github repo name is a bit more difficult, I would say the name is quite clear, and renaming it to 'openeo' or 'openeo-api' is not really a good option either as that would be even more confusing?

**Comment by soxofaan** [comment]
I was thinking the same. There is little reason to change the github repo name.
But synchronizing the pip package name with the module name makes things less confusing.
As far I currently understand, the repo is not only about the python client, but also used as a "common" lib in openeo-python-driver and openeo-geopyspark-driver, so it makes sense to just call it "openeo"

**Comment by jdries** [comment]
Maybe we should do a release with the current name, and then immediately also do a release with the new name. That way users have a window in time where an up to date version is available for both names, and can migrate their projects.

**Comment by soxofaan** [comment]
> do a release with the current name, and then immediately also do a release with the new name

I'm not sure that is even necessary. As far as I can guess users install the package using `git clone + pip install path/to/clone` instead of installing a release (e.g.. Consequently, they are not really confronted with the name `openeo-api` itself during installation. The only place might be in a `requirements.txt` file where `openeo-api` is listed explicitly (e.g. https://github.com/Open-EO/openeo-geopyspark-driver/blob/c22be09ba0ea1d1be92c5d7b94e663286aaec6f8/requirements.txt#L9)

**Comment by soxofaan** [comment]
(sorry pressed wrong button)

**Comment by soxofaan** [comment]
> Maybe we should do a release with the current name, and then immediately also do a release with the new name. 

I'm wondering if this is even necessary. I would guess most users install openeo python client with `git clone + pip install path/to/clone` instead of `pip install` of a release. Consequently they are not really confronted with `openeo-api` as a name currently.

**Comment by jdries** [comment]
by working on the deployment pipeline, I just released openeo-api 0.0.5 (kind of accidentally, but it just happens whenever you increase the version number)
So we can go ahead and rename the package, this will also trigger creation of openeo 0.0.5
