### ISSUE TITLE
UDP based job manager

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-python-client#604]
Support a job manager that automatically creates jobs based on the schema of a UDP.

Prototype is already available here, with some valid comments that should be taken into account:
https://github.com/ESA-APEx/esa-apex-toolbox-python/pull/1

**Comment by JeroenVerstraelen** [comment]
There is a PR, just needs small adjustments.

**Comment by soxofaan** [comment]
worked on PR at https://github.com/Open-EO/openeo-python-client/pull/644

**Comment by soxofaan** [comment]
https://github.com/Open-EO/openeo-python-client/pull/644 is ready for review/mering I think

**Comment by soxofaan** [comment]
merged #644
