### ISSUE TITLE
Datacubes lack metadata information - access to datacube product information

### ISSUE THREAD

**Issue by hobbitsyfeet** [Open-EO/openeo-python-client#615]
I am coming over from Copernicus sentinelsat and I am having some trouble getting the desired information from collections and datacubes. For example, I find I am left wondering which date and time I have collected within the temporal intervals. I access the `flat_graph()` function, which only returns information I know since I have specified in the `load_collection()` function. accessing datacube.metadata returns some metadata that has some wrong information, specifically in the temporal interval. 

For example, I request this information (spatial extent is just w,x,y,z).
```
cube = connection.load_collection(
        "SENTINEL2_L1C",
        spatial_extent={"west": w, "south": x, "east": y, "north":  z},
        temporal_extent = ["2024-10-01", "2024-10-06"],
        bands=[ "B03", "B11"],
        max_cloud_cover=85,
    )
```
Note the date:

`CollectionMetadata({'spatial': {'bbox': [[w,x,y,z]]}, 'temporal': {'interval': [['2015-07-04T00:00:00Z', None]]}} - ['B03', 'B11'] - ['bands', 't', 'x', 'y'])`

Meanwhile, I am still left to guess which dates are collected in the datacube. I could individually collect dates in a list of collections, but there is no way to get a query to access those dates, which leaves me trial and error. Functions such as `datacube.count_time()`, `datacube.min_time()`, `datacube.median_time()`, and `datacube.max_time()` are somewhat vague, and I still cannot get it to spit out the dates of each cube within `datacube.count_time()`

Meanwhile, I know information about Sentinel products exists in much more detail. Most importantly, the date and footprint of the satellite data which recorded the data. 
```
{'Acquisition Type': 'NOMINAL',
 'Carrier rocket': 'Soyuz',
 'Cycle number': 107,
 'Date': datetime.datetime(2017, 4, 25, 15, 56, 12, 814000),
 'Filename': 'S1A_IW_SLC__1SDV_20170425T155612_20170425T155639_016302_01AF91_46FF.SAFE',
 'Footprint': '<gml:Polygon srsName="http://www.opengis.net/gml/srs/epsg.xml#4326" xmlns:gml="http://www.opengis.net/gml">\n   <gml:outerBoundaryIs>\n      <gml:LinearRing>\n         <gml:coordinates>0.401648,34.322010 0.876987,36.540989 -0.747357,36.884121 -1.227940,34.664474 0.401648,34.322010</gml:coordinates>\n      </gml:LinearRing>\n   </gml:outerBoundaryIs>\n</gml:Polygon>',
 'Format': 'SAFE',
 'Identifier': 'S1A_IW_SLC__1SDV_20170425T155612_20170425T155639_016302_01AF91_46FF',
 'Ingestion Date': datetime.datetime(2017, 4, 25, 19, 23, 45, 956000),
 'Instrument': 'SAR-C',
 'Instrument abbreviation': 'SAR-C SAR',
 'Instrument description': '<a target="_blank" href="https://sentinel.esa.int/web/sentinel/missions/sentinel-1">https://sentinel.esa.int/web/sentinel/missions/sentinel-1</a>',
 'Instrument description text': 'The SAR Antenna Subsystem (SAS) is developed and build by AstriumGmbH. It is a large foldable planar phased array antenna, which isformed by a centre panel and two antenna side wings. In deployedconfiguration the antenna has an overall aperture of 12.3 x 0.84 m.The antenna provides a fast electronic scanning capability inazimuth and elevation and is based on low loss and highly stablewaveguide radiators build in carbon fibre technology, which arealready successfully used by the TerraSAR-X radar imaging mission.The SAR Electronic Subsystem (SES) is developed and build byAstrium Ltd. It provides all radar control, IF/ RF signalgeneration and receive data handling functions for the SARInstrument. The fully redundant SES is based on a channelisedarchitecture with one transmit and two receive chains, providing amodular approach to the generation and reception of wide-bandsignals and the handling of multi-polarisation modes. One keyfeature is the implementation of the Flexible Dynamic BlockAdaptive Quantisation (FD-BAQ) data compression concept, whichallows an efficient use of on-board storage resources and minimisesdownlink times.',
 'Instrument mode': 'IW',
 'Instrument name': 'Synthetic Aperture Radar (C-band)',
 'Instrument swath': 'IW1 IW2 IW3',
 'JTS footprint': 'POLYGON ((34.322010 0.401648,36.540989 0.876987,36.884121 -0.747357,34.664474 -1.227940,34.322010 0.401648))',
 'Launch date': 'April 3rd, 2014',
 'Mission datatake id': 110481,
 'Mission type': 'Earth observation',
 'Mode': 'IW',
 'NSSDC identifier': '2014-016A',
 'Operator': 'European Space Agency',
 'Orbit number (start)': 16302,
 'Orbit number (stop)': 16302,
 'Pass direction': 'ASCENDING',
 'Phase identifier': 1,
 'Polarisation': 'VV VH',
 'Product class': 'S',
 'Product class description': 'SAR Standard L1 Product',
 'Product composition': 'Slice',
 'Product level': 'L1',
 'Product type': 'SLC',
 'Relative orbit (start)': 130,
 'Relative orbit (stop)': 130,
 'Satellite': 'Sentinel-1',
 'Satellite description': '<a target="_blank" href="https://sentinel.esa.int/web/sentinel/missions/sentinel-1">https://sentinel.esa.int/web/sentinel/missions/sentinel-1</a>',
 'Satellite name': 'Sentinel-1',
 'Satellite number': 'A',
 'Sensing start': datetime.datetime(2017, 4, 25, 15, 56, 12, 814000),
 'Sensing stop': datetime.datetime(2017, 4, 25, 15, 56, 39, 758000),
 'Size': '7.1 GB',
 'Slice number': 8,
 'Start relative orbit number': 130,
 'Status': 'ARCHIVED',
 'Stop relative orbit number': 130,
 'Timeliness Category': 'Fast-24h',
 'date': datetime.datetime(2017, 4, 25, 15, 56, 12, 814000),
 'footprint': 'POLYGON((34.322010 0.401648,36.540989 0.876987,36.884121 -0.747357,34.664474 -1.227940,34.322010 0.401648))',
 'id': '04548172-c64a-418f-8e83-7a4d148adf1e',
 'md5': 'E5855D1C974171D33EE4BC08B9D221AE',
 'size': 4633501134,
 'title': 'S1A_IW_SLC__1SDV_20170425T155612_20170425T155639_016302_01AF91_46FF',
 'url': "https://apihub.copernicus.eu/apihub/odata/v1/Products('04548172-c64a-418f-8e83-7a4d148adf1e')/$value"}
```
   
   
   Nonetheless, I am having this issue where I feel like I need to integrate much more work myself just to try and extract relatively simple information. I say this because knowing the exact time/dates is critical to nearly every application, and I feel like this should be the first step in documentation and tutorials.

**Comment by jdries** [comment]
Hi,
your question has a couple of answers actually. Most importantly, I would recommend reading one of the introductions to what openEO is and how it works. This mooc is for instance a great resource: https://eo-college.org/courses/cubes-and-clouds/

You won't find any observation dates after calling load_collecton, because it only builds the workflow, but does not execute anything. When you would however download it as a netCDF (I recommend ot use a small spatiotemporal extent for starters), then it will contain the dates you are looking for.

In most cases, algorithms that depend on observation times will use one of the processes working on the 'time' dimension, for instance to run a user defined function which then gets all the retrieved dates together with the data.

Users that really need to know dates up front, will typically query the catalog directly, using a tool like sentinelsat, and then get back to processing in openEO.

Finally, there is also the 'dimension_labels' process, which can return observation dates.

I'll close the issue for now, note that this kind of questions can also be asked on platform forums, like forum.dataspace.copernicus.eu.
