### ISSUE TITLE
how to connect with Google Earth Engine

### ISSUE THREAD

**Issue by jome1** [Open-EO/openeo-python-client#616]
Dear Community,

I want to connect to the Google Earth Engine via the python openeo API. The [documentation](https://openeo.org/documentation/1.0/python/#processes) is not detailed enough for this.

The Google Earth Engine implementation for openEO only supports Basic authentication. So you would use the following code for the connection:
```
import openeo

connection = openeo.connect("https://earthengine.openeo.org")
connection.authenticate_basic("username", "password")
```

Which username and password do I have to use? 
The documentation refers to this [link](https://github.com/Open-EO/openeo-earthengine-driver#demo). There is a link to [register for GEE](https://signup.earthengine.google.com/). But then I only create a new cloud project with my google account.
Using my google mail address and my password in the code above for the connection does not work.

**Comment by soxofaan** [comment]
@m-mohr  I think this question better belongs under the https://github.com/Open-EO/openeo-earthengine-driver project, but I can not transfer it there

**Comment by jome1** [comment]
Thanks for the info!
I posted it there too. 
You can close this issue if you want.

**Comment by m-mohr** [comment]
Answered it here: https://github.com/Open-EO/openeo-earthengine-driver/issues/91#issuecomment-2343697775

Unfortunately, the Python client doesn't really support the OIDC flows yet that Google exposes (implicit or other flows without  PKCE).

**Comment by soxofaan** [comment]
indeed the "implicit" flow is not supported by python client

at https://accounts.google.com/.well-known/openid-configuration I see that "device_code" flow is supported, so that could work with the Python client. However, it requires a client id to work with, which is cumbersome for regular users to obtain

**Comment by m-mohr** [comment]
Yes, it's device_code without PKCE, so it's indeed annoying because you need a secret if I remember correctly and that makes it pretty user-unfriendly because we can't use auto-discovery via the openEO API. Google's OIDC implementation just sucks.
