### ISSUE TITLE
openeo.version() - attribute not updated to 0.4.0

### ISSUE THREAD

**Issue by MilutinMM** [Open-EO/openeo-python-client#65]
Hi all,
I downloaded the openEO python client 0.4.0 version (the zip file) and after running "openeo.version()" I got 0.3.0. 
It might be that openeo.version() attribute is not updated...
Generally, it does not stop one to work further, but it might be confusion.

**Comment by m-mohr** [comment]
According to https://open-eo.github.io/openeo-api/draft/guidelines-clients/
openeo.clientVersion() should give the version of the client, so 0.4.0 if that's the version of the client.
capabilities.apiVersion() should give the supported API version, e.g. 0.4.2 if the most recent release is implemented.
capabilities.backendVersion() should give a version number for the back-end, e.g. 1.0.0

**Comment by soxofaan** [comment]
`openeo.version()` is removed now to avoid confusion. Instead:
```
>>> import openeo
>>> openeo.client_version()
'0.0.5'
```
