### ISSUE TITLE
Job Manager: status histograms

### ISSUE THREAD

**Issue by DeRooBert** [Open-EO/openeo-python-client#655]
@soxofaan  It seems that the histograms of the statusses in a csv files were removed in version 0.32.0. This was a very usefull feature to follow-up large scale processing, as such can this be reimplemented or was there a good reason to remove it?

**Comment by soxofaan** [comment]
Can you give an example snippet of what used to work for you and now doesn't?

**Comment by soxofaan** [comment]
I'm not even sure we had some status histogram functionality before 0.32.0

**Comment by DeRooBert** [comment]
https://github.com/Open-EO/openeo-python-client/blob/v0.31.0/openeo/extra/job_management.py#L344 and L345. This has been removed in version v0.32.0. and created a histrogram like this: 
![image](https://github.com/user-attachments/assets/9adfdc74-f181-46d6-afa9-1d0be84834f1)
which makes it easier to follow-up the processing progress.

**Comment by soxofaan** [comment]
ah ok, you mean the logging of that histogram, that was indeed removed by https://github.com/Open-EO/openeo-python-client/pull/607

but it indeed makes sense to add this functionality back

**Comment by soxofaan** [comment]
restored with aa3e653
