### ISSUE TITLE
 Large NoData Areas in TIFF Files Downloaded from OpenEO in Python

### ISSUE THREAD

**Issue by paulasanchezgt** [Open-EO/openeo-python-client#659]
Hello everyone,

I've been downloading TIFF files (Bands in TIFF format) using OpenEO in Python, and although the files seem correctly formatted, I'm encountering a major issue: many pixels show as NoData. Depending on the date I select, I often get only a small square of actual data, while the rest of the spatial extent has NoData.

Interestingly, if I manually download the same area and time range from the Copernicus Browser, I get data across the entire spatial extent.

Does anyone know why this discrepancy is happening between OpenEO and the Copernicus Browser? Is there a specific setting in OpenEO that might be causing this, or a configuration issue in Python?

Thanks a lot for any insights!

**Comment by bossie** [comment]
Hi @paulasanchezgt,

This does not sound like an issue with the OpenEO Python client but rather the OpenEO back-end. In this case it's recommended to use the Copernicus Data Space Ecosystem help center at https://helpcenter.dataspace.copernicus.eu/hc/en-gb and especially its forum at https://forum.dataspace.copernicus.eu/.

Make sure to include a snippet of your code; that makes it possible to pinpoint exactly where you are experiencing problems.
