### ISSUE TITLE
Load_collection check for spatial extent with crs != 4326

### ISSUE THREAD

**Issue by ValentinaHutter** [Open-EO/openeo-python-client#670]
When I try to use `load_collection` with a `spatial_extent` with a crs other than 4326, e.g.
```
spatial_extent = dict(
    west=679720, east=680680, south=5151080, north=5151920, crs="EPSG:32632"
)
```

 I get the following warning: 

```
Preflight process graph validation failed: [500] Internal Error: {"code":"RequestValidationError","description":"[{'loc': ('body', 'bbox'), 'msg': 'Bounding box must be within (-180, -90, 180, 90)', 'type': 'value_error'}]"}
``` 

Is this related to the metadata in my collection and do we need to add something to our backend's collections endpoints or is this a general check for all requests? As far as I know, the backends can also handle requests with crs like the one above.

**Comment by bossie** [comment]
Hi Valentina,

This is the Python client calling the back-end's `/validation` endpoint with a process graph. It's actually an error returned from the back-end but it does not prevent your job from running; rather it manifests itself as a warning.

If the string `"EPSG:32632"` does not work, you might want to try the number `32632`, (that is how `load_collection`'s crs parameter is defined) but this is back-end specific behavior.

Either way, this is not a client issue.

**Comment by ValentinaHutter** [comment]
Thanks for the quick reply, then I will open an internal issue and investigate further!
