### ISSUE TITLE
Inaccurate Progress Count

### ISSUE THREAD

**Issue by YasserInSpace** [Open-EO/openeo-python-client#695]
The progress count for jobs is inaccurate. It remains at 0% for an extended period after creation and then abruptly jumps to 100% upon completion. This behavior is not helpful for monitoring job progress.
The progress count should provide a more accurate representation of the job's progress throughout its execution. It should update periodically with meaningful values (e.g., 25%, 50%, 75%) to reflect the job's progress.

![image](https://github.com/user-attachments/assets/28704b2a-80c7-4e5a-ba7e-6e13ef3c6c65)

**Comment by soxofaan** [comment]
Note that providing the progress fraction is responsibility of the openEO backend, the client can not do much about that. As you see in the screenshot you provided, the client gives a best effort guess (0% when created, 100% when finished), but if the backend does not provide runtime progress, the client can't guess and shows "N/A" (not available)
