### ISSUE TITLE
Drop support for pre-0.4 API?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#72]
Open question: is it necessary to keep supporting 0.3-style API in the python client? I have not really an idea whether there are actual users that use the python client with 0.3-only backends.

There are quite some differences between the 0.3 and 0.4 versions of the API (how process graphs work, terminology, etc), and supporting both in the python client code makes things a bit tedious and hard to maintain.

It would benefit speed of development and code quality if we could get rid of all the 0.3-related code and implementation details.

**Comment by m-mohr** [comment]
None of the other clients (except the openEO Hub) support multiple versions. For the time of heavy API changes / development, I'd say users of the 0.3 API could simply use the latest version available that supports 0.3. Of course that means there must be a release for it, which is available for all other clients except Python.

So action items could be:
1. Release a version that supports 0.3
2. Drop 0.3 support
3. Align with 0.4 and do another release

**Comment by jdries** [comment]
Releases of the python client do exist:
https://artifactory.vgt.vito.be/webapp/#/artifacts/browse/simple/General/python-openeo/openeo/0.0.5
also for older versions:
https://artifactory.vgt.vito.be/webapp/#/artifacts/browse/simple/General/python-openeo/openeo-api/0.0.4

so feel free to stop supporting 0.3, and start with cleaning code where needed.

**Comment by m-mohr** [comment]
Aha, I thought there were none because I couldn't fine them on PyPI.

**Comment by jdries** [comment]
Could no longer find major pre 0.4.0 pieces of code, so considering this fixed.
