### ISSUE TITLE
Clean up band handling/filtering 

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#76]
The python client is currently quite confusing concerning band handling/filtering:
- `ImageCollection.band_filter(bands)` expects a list of band names according to the docs. However the only way I actually get this function to work is with a single integer `0`. When specifying a list of strings I get `java.lang.String cannot be cast to java.lang.Integer`, when specifying a single string I get error `('band must be an int, tuple, or list. Recieved', <class 'str'>, 'instead.')`, when specifying an int other than 0 I get `Band 1 does not exist`
- `ImageCollection.band(name)` expects a band name (string) and works properly
- the current (0.4.2) spec defines actually the process `filter_bands` (not `band_filter`) and defines three possible arguments for band selection: `bands`, `common_names` and `wavelengths` https://open-eo.github.io/openeo-api/processreference/#filter_bands

I think it's best to get these things more in harmony

**Comment by Jaapel** [comment]
Not sure what the progress of this ticket is, but I still receive errors when using `.filter_bands(str)`. Luckily, the `.band(str)` function works well.

**Comment by soxofaan** [comment]
Most original issues should be covered by now.

> but I still receive errors when using .filter_bands(str)
what kind of errors and can you provide the steps to reproduce?

**Comment by Jaapel** [comment]
```
from openeo import connect, Connection
from openeo.rest.datacube import DataCube
from typing import Dict, Union, List
import pathlib

vito_url: str = "https://openeo.vito.be/openeo/1.0"
con: Connection = connect(vito_url)
con.authenticate_oidc(provider_id="egi")

out_dir = pathlib.Path("output")
out_dir.mkdir(parents=True, exist_ok=True)

denia_harbour_bbox: Dict[str, Union[float, str]] = {"west": 0.10594089795383788, "east": 0.12937267590793944, "south": 38.83464299556706, "north": 38.85035302841166, "crs": "EPSG:4326"}
temporal_extent: List[str] = ["2020-08-01", "2021-01-01"]

collection = ("LANDSAT8_L1C", ["B06", "B05", "B03"])
band_names: str = ["swir1", "nir", "green"]
dc: DataCube = con.load_collection(
        collection_id=collection[0],
        spatial_extent=denia_harbour_bbox,
        temporal_extent=temporal_extent,
        bands=collection[1]
    ).add_dimension(name="source_name", label=collection[0], type="other") \
    .rename_labels(dimension="bands", source=collection[1], target=band_names)

green: DataCube = dc.filter_bands("green")
nir: DataCube = dc.filter_bands("nir")
ndwi: DataCube = (green - nir) / (green + nir)

ndwi.download(out_dir / "test.nc", format="netcdf")
```

**Comment by soxofaan** [comment]
@Jaapel :

First of all, your script seems to work against the dev instance of the VITO backend (https://openeo-dev.vito.be/openeo/1.0).

Secondly and more importantly, the way you are computing `ndwi` here is not recommended. 
You should use `.bands()` instead of `.filter_bands()`.
 `.bands()` is intended to do (spectral) "band math": doing calculations with values from spectral bands expressed with python math symbols (`-` and `/` in your case):
```
green: DataCube = dc.band("green")
nir: DataCube = dc.band("nir")
ndwi: DataCube = (green - nir) / (green + nir)
```
This will be translated to a `reduce_dimension` operation along the "bands" dimension, so that your 4D datacube (t,x,y,bands) is converted to a 3D data cube (t,x,y), holding the ndwi values, which is what you want.


With `filter_bands()`, there is no `reduce_dimension`, but the math operations are currently  translated to a `merge_cubes` process with an overlap resolver. And while this appears to work on our dev instance, it should actually *not* work according to the spec. I'll probably have to file a separate bug for this.

**Comment by soxofaan** [comment]
I think it's fine to close this old/outdated issue now.
