### ISSUE TITLE
Handling of Asynchronous job calls (batch job)

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-python-client#9]
How should asynchronous batch jobs (see in the [coreAPI doc](https://open-eo.github.io/openeo-api/jobs/index.html) be handled in the python client ? 
Workflow: commit job -> queue job -> when job has finished: get jobs data
Some possibilities on my opinion:

- Let the user himself handle it, so only provide a call for trying to get the result. (quick and dirty but not really practical)
- Use Python signals/queue/threading, signals are basically pythons way of handling asynchronous workflows.

**Comment by m-mohr** [comment]
Make sure to check for the current API version. The jobs were significantly redesigned. You may want to build upon the not yet finished subscriptions to get notified whenever a job has finished and is ready for downloading.

**Comment by jdries** [comment]
This method: openeo.rest.imagecollectionclient.ImageCollectionClient#execute_batch
now helps the user to run a batch job and retrieve the result, in a similar manner to synchronous jobs.

Anything more complex is currently not supported by (most) backends.
