### ISSUE TITLE
how to use save_result ?

### ISSUE THREAD

**Issue by lforesta** [Open-EO/openeo-python-client#91]
save_result is listed in the processes, but I am not sure how one can use it.

I get this error when running the process graph copied below:
```
output = min_evi.save_result()
AttributeError: 'ImageCollectionClient' object has no attribute 'save_result'
```

Process graph:
```
import json
import openeo

vito_url = 'http://openeo.vgt.vito.be/openeo/0.4.0'
collection_id = 'CGS_SENTINEL2_RADIOMETRY_V102_001'

session = openeo.connect(vito_url)

minx = 2.052030657924054
maxx = 4.063236553549667
maxy = 51.00726308446294
miny = 50.99458367677388
epsg = "EPSG:4326"
s2_radiometry = session.imagecollection(collection_id) \
                    .filter_temporal("2018-06-04","2018-06-23") \
                    .filter_bbox(west=minx,east=maxx,north=maxy,south=miny,crs=epsg)
B02 = s2_radiometry.band('2')
B04 = s2_radiometry.band('4')
B08 = s2_radiometry.band('8')

evi_cube = (2.5 * (B08 - B04)) / ((B08 + 6.0 * B04 - 7.5 * B02) + 1.0)
min_evi = evi_cube.min_time()
final_pg = min_evi.graph

output = min_evi.save_result()
final_pg = output.graph

#print(json.dumps(final_pg,indent=2))
with open('out_pg.json', 'w') as outfile:
    json.dump(final_pg, outfile)
```

**Comment by jdries** [comment]
It's indeed confusing, current recommendation is to simply use the 'download' method, as shown in the example in our documentation:
https://open-eo.github.io/openeo-python-client/

**Comment by lforesta** [comment]
Thanks for the info.
Actually I was trying to simply write the process graph and see its json output, before submitting/evaluating the job. The download method does both together apparently, but I was able to isolate the line I need in it: `newcollection = self.graph_add_process("save_result",args)`

**Comment by soxofaan** [comment]
I think this issue is not valid anymore (e.g. `save_result` is method on `DataCube` now, and there are plenty of examples of how results can be downloaded)
