### ISSUE TITLE
array_element - multiple identical nodes in process graph

### ISSUE THREAD

**Issue by lforesta** [Open-EO/openeo-python-client#92]
Maybe this is the intended behavior, but when using the array_element process, identical nodes are created several times. Using the [phenology](https://github.com/Open-EO/openeo-python-client/blob/master/examples/phenology_example.py) example as a basis, the process graph copied below is an example of this behavior.

B08 is created once and then used twice when creating cube_1. However if one checks the json output, there are three array_element nodes, two of which pointing to the same data (band 8 in the collection).

Is this intended? It does _not_ affect the end result.

Process graph:
```
import json
import openeo

vito_url = 'http://openeo.vgt.vito.be/openeo/0.4.0'
collection_id = 'CGS_SENTINEL2_RADIOMETRY_V102_001'

session = openeo.connect(vito_url)

minx = 2.052030657924054
maxx = 4.063236553549667
maxy = 51.00726308446294
miny = 50.99458367677388
epsg = "EPSG:4326"
s2_radiometry = session.imagecollection(collection_id) \
                    .filter_temporal("2018-06-04","2018-06-23") \
                    .filter_bbox(west=minx,east=maxx,north=maxy,south=miny,crs=epsg)
B02 = s2_radiometry.band('2')
B04 = s2_radiometry.band('4')
B08 = s2_radiometry.band('8')

cube_1 = B08 + B04 + B08

print(json.dumps(cube_1.graph,indent=2))
```

**Comment by jdries** [comment]
Yes, we know about this, my first implementation tried to avoid this duplication, but that resulted in issues later on. So I had to solve it like this for now.

**Comment by soxofaan** [comment]
closing this ticket (for now)
main ticket to address the underlying issue: #117
