### ISSUE TITLE
hard-coded dimension name in ImageCollectionClient.band()

### ISSUE THREAD

**Issue by lforesta** [Open-EO/openeo-python-client#93]
The band() method (which is a reduce over the spectral dimension) hard-codes "spectral_bands" as the dimension name for the spectral dimension of a collection. However, this info should be read from the collection metadata of the backend, since it may vary.
An option would be to send a request to /collections/collection_name when the load_collection() method is used in the client and store the collection metadata locally (temporarily, just for the current session).

Related to [issue 25 in openeo-python-driver](https://github.com/Open-EO/openeo-python-driver/issues/25)

**Comment by soxofaan** [comment]
Under #77 I already improved metadata handling in the client, so what you suggest should be pretty straightforward

**Comment by soxofaan** [comment]
related: Open-EO/openeo-api#208 Open-EO/openeo-processes#77

**Comment by soxofaan** [comment]
Update: it's less straightforward as I hoped because the metadata (possibly) changes with every operation, which is not yet implemented. For example, when you do bit of basic "band math" the metadata ends up empty at some point and things break down.

**Comment by jdries** [comment]
The issue here is with the dimension name, in the latest workshop, we decided to use 'bands' for this well known dimension.
We should fix this in our backend and in the client as well.

**Comment by soxofaan** [comment]
minor note: the API spec only recommends the dimension name "bands", it does not enforce it (as far as I currently understand). So while this is clearly better and fixes the original issue for most cases, it still might pop up later.

**Comment by soxofaan** [comment]
merged the fixes in master
