### ISSUE TITLE
Token not sent to /result endpoint

### ISSUE THREAD

**Issue by lforesta** [Open-EO/openeo-python-client#95]
It seems Collection.download() sends a request to the /result endpoint (sync processing) without sending a token:
```
r = requests.post(download_url, json=request, stream = True, timeout=1000 )
```
This works only for back-ends without authentication (e.g. VITO) but not for e.g. EURAC, returning:
`ConnectionAbortedError: None`

Doing the following works (for basic auth):
```
auth_response = requests.get(backend_url + "credentials/basic", auth=(username, password))
auth_content = json.loads(auth_response.text)
access_token = auth_content["access_token"]
job_response = requests.post(backend_url + "/result", json=job, headers={'Authorization': f'Bearer {access_token}'})
```

**Comment by soxofaan** [comment]
This should be already be addressed by a fix I did some time ago ago: 515a623

which version are you using: a pip install or an installed git clone?

**Comment by lforesta** [comment]
git clone from master
Shouldn't the headers (with the token) be included in the request? I don't see that in the commit you linked.

I see in RestApiConnection.post() that indeed a request Python's requests with **kwargs is sent:
`return self.request("post", path=path, json=json, **kwargs)`
so the headers could be added to any request.

However, when that method is used inside ImageCollectionClient.dowload(), no kwargs (here format_options) are passed.

I can provide an example for this using the EURAC back-end if needed

**Comment by soxofaan** [comment]
the commit I referred to was indeed basically just a change from `request.post` to `self.post`, but that `self.post` should take care of passing the auth header, which is handled generically by `RestApiConnection.request` : 
https://github.com/Open-EO/openeo-python-client/blob/37f98d05d60f2565a53798bbde9bddb702938acf/openeo/rest/connection.py#L67-L75

**Comment by soxofaan** [comment]
Note that the auth headers are actually injected by the auth object (a property which is set on the RestApiConnection object from the authentication methods):
https://github.com/Open-EO/openeo-python-client/blob/37f98d05d60f2565a53798bbde9bddb702938acf/openeo/rest/auth/auth.py#L24-L36

**Comment by soxofaan** [comment]
I tested it with the latest master of the python client and I see a "Authorization" header passing by on the download request (`/result` endpoint)

**Comment by soxofaan** [comment]
Added unit test about passing bearer token with download/result request:  1a5fcc5 

please reopen if there is still an issue
